import json

cases = [
dict(id="base44", founders=["Maor Shlomo"], product="Base44", domain="AI 앱 빌더 (바이브코딩 플랫폼)",
     one_liner="프롬프트만으로 백엔드/DB/인증까지 포함된 풀스택 앱을 생성해주는 노코드 AI 플랫폼",
     team_size="1인 (솔로, 후반부 소수 채용)", region="이스라엘",
     revenue="월 순이익 $189,000(2025-05), 누적매출 약 $1.9M; 6개월만에 Wix에 현금 $80M + 최대 $90M 언아웃으로 인수",
     revenue_date="2025-05 / 2025-06 exit", exit_status="acquired (Wix, $80M)",
     stack=["AI 코드생성 (Claude/OpenAI 계열 추정)"], ai_tools=["Claude", "ChatGPT/OpenAI"],
     founder_background="31세 개발자, 이전에 데이터사이언스 스타트업 Explorium 공동창업(총 $125M 투자유치) 경험 있는 연쇄창업가",
     business_model="프리미엄/사용량 기반 SaaS(AI 앱 생성 크레딧)",
     sources=["https://techcrunch.com/2025/06/18/6-month-old-solo-owned-vibe-coder-base44-sells-to-wix-for-80m-cash",
               "https://www.wix.com/press-room/home/post/wix-further-expands-into-vibe-coding-with-acquisition-of-base44-a-hyper-growth-startup-that-simplif",
               "https://www.lennysnewsletter.com/p/the-base44-bootstrapped-startup-success-story-maor-shlomo"],
     confidence="high"),

dict(id="pieter-levels-portfolio", founders=["Pieter Levels"], product="Nomad List / RemoteOK / Photo AI / Interior AI (포트폴리오)",
     domain="원격근무 커뮤니티 + AI 이미지 생성 SaaS 포트폴리오",
     one_liner="디지털 노마드 커뮤니티/구인 플랫폼과 AI 사진·인테리어 생성 서비스 등 수십 개 제품을 혼자 운영",
     team_size="1인 (직원 없음, 간헐적 계약직)", region="네덜란드 (발리 거주 노마드)",
     revenue="Photo AI 18개월 만에 MRR $132K 도달; 포트폴리오 전체 연 매출 약 $3M 수준으로 다수 매체에서 인용",
     revenue_date="2023-2025 누적", exit_status="운영 중",
     stack=["PHP/SQLite", "vanilla JS/jQuery", "단일 VPS"], ai_tools=["Stable Diffusion", "DreamBooth", "Replicate", "GPT-4 API"],
     founder_background="네덜란드 출신, 유튜버에서 개발자로 전환, 70개 이상 실패작 이후 히트작들을 만든 대표적 '빌드 인 퍼블릭' 인플루언서",
     business_model="구독형 SaaS 다수 (프리미엄 티어, 무료 없음)",
     sources=["https://www.indiehackers.com/post/photo-ai-by-pieter-levels-complete-deep-dive-case-study-0-to-132k-mrr-in-18-months-3a9a2b1579",
               "https://levels.io/photoai-40870-line-index-php-105k-mo-revenue",
               "https://ppc.land/how-one-photo-ai-app-generates-132k-monthly-after-70-failed-startups/"],
     confidence="high"),

dict(id="headshotpro", founders=["Danny Postma"], product="HeadshotPro", domain="AI 프로필사진 생성",
     one_liner="링크드인/기업용 전문 프로필 사진을 AI로 생성해주는 서비스",
     team_size="1인 (솔로/매우 린)", region="네덜란드 (발리 거주)",
     revenue="월 약 $300,000 (연 $3.6M ARR 수준)", revenue_date="2024-2025", exit_status="운영 중",
     stack=["생성형 이미지 AI 모델(구체 미상세)"], ai_tools=["unknown"],
     founder_background="이전에 AI 카피라이팅 툴 Headlime을 만들어 8개월만에 약 $1M에 매각한 연쇄창업가",
     business_model="패키지 단위 일회성 결제 (AI 사진 생성 서비스)",
     sources=["https://www.starterstory.com/stories/headshotpro-breakdown",
               "https://supabird.io/articles/danny-postma-how-a-solo-hacker-built-an-ai-empire-from-bali"],
     confidence="medium"),

dict(id="cal-ai", founders=["Zach Yadegari", "Henry Langmack", "Blake Anderson", "Jake Castillo"], product="Cal AI",
     domain="AI 칼로리/영양 트래킹 앱", one_liner="음식 사진을 찍으면 AI가 칼로리/영양성분을 분석해주는 모바일 앱",
     team_size="공동창업자 4명 + 직원 소수(최대 약 8~12명)", region="미국",
     revenue="월 매출 $2M+ (2025-03 기준, 일부 소스는 연 $30-40M ARR로 인용); MyFitnessPal에 인수(2026-03, 금액 비공개)",
     revenue_date="2025-03 ~ 2026-03", exit_status="acquired (MyFitnessPal)",
     stack=["이미지인식 AI(Anthropic/OpenAI 계열)", "RAG", "오픈소스 식품DB"], ai_tools=["Anthropic", "OpenAI"],
     founder_background="공동창업자 다수가 고등학생 시절 창업; Yadegari는 16세에 이전 서비스를 $100K에 매각한 경험 있는 자수성가형 개발자",
     business_model="프리미엄 모바일 앱 구독",
     sources=["https://techcrunch.com/2025/03/16/photo-calorie-app-cal-ai-downloaded-over-a-million-times-was-built-by-two-teenagers/",
               "https://techcrunch.com/2026/03/02/myfitnesspal-has-acquired-cal-ai-the-viral-calorie-app-built-by-teens/",
               "https://www.entrepreneur.com/business-news/teen-builds-30-million-app-gets-rejected-by-15-colleges/489644"],
     confidence="high"),

dict(id="cluely", founders=["Chungin (Roy) Lee", "Neel Shanmugam", "Alex Chen"], product="Cluely",
     domain="AI 실시간 어시스턴트 (화면/오디오 모니터링 후 답변 제안)",
     one_liner="면접·회의 중 화면과 음성을 보고 실시간으로 답변을 제안해주는 투명 오버레이 AI 어시스턴트 (초기엔 '면접 커닝툴'로 시작)",
     team_size="소규모 초기팀", region="미국",
     revenue="시드 $5.3M(2025-04) + 시리즈A $15M(2025-06, a16z), 누적 $20.3M 투자유치; ARR $7M 주장했으나 실제로는 약 $5.2M로 확인됨",
     revenue_date="2025", exit_status="운영 중 (논란 있음)",
     stack=["LLM 기반"], ai_tools=["unknown"],
     founder_background="Lee와 Shanmugam은 이 제품의 전신인 'Interview Coder'(면접용 AI 부정행위 툴) 개발로 컬럼비아대에서 정학 처분",
     business_model="구독형 SaaS",
     sources=["https://en.wikipedia.org/wiki/Cluely",
               "https://www.inc.com/leila-sheridan/an-a16z-backed-startup-that-helps-people-cheat-on-job-interviews-just-got-caught-in-a-7-million-lie-the-ceo-was-sweating/91313070"],
     confidence="medium"),

dict(id="marc-lou-portfolio", founders=["Marc Lou"], product="ShipFast + 인디 제품 포트폴리오",
     domain="SaaS 보일러플레이트/스타터 킷 + 다수 소규모 앱",
     one_liner="빠른 SaaS 런칭을 위한 Next.js 보일러플레이트 판매 및 다수의 사이드 프로젝트 운영",
     team_size="1인", region="프랑스",
     revenue="ShipFast 4개월간 $528K 보고; 2025년 연 매출 $1,032,000 (본인 뉴스레터 2026-01-04 공개, 2024년 대비 20% 감소) — 내역: CodeFast 월 약 $20K, ShipFast 월 약 $20K, DataFast MRR $15.8K, TrustMRR(24시간 제작) 런칭 후 MRR $25K 정점; 본인 월별 공개 예: 2025-07 $48,921, 2025-10 $66,040",
     revenue_date="2023-2025", exit_status="운영 중",
     stack=["Next.js"], ai_tools=["unknown"],
     founder_background="프랑스 출신 대표적 '빌드 인 퍼블릭' 인디해커",
     business_model="보일러플레이트/템플릿 일회성 판매 + 사이드 SaaS 구독",
     sources=["https://www.starterstory.com/marc-lou-shipfast",
               "https://newsletter.marclou.com/p/i-made-250000-usd-selling-javascript",
               "https://newsletter.marclou.com/p/i-made-1-032-000-in-2025",
               "https://x.com/marc_louvion/status/1984327198774616533"],
     confidence="high"),

dict(id="tweethunter-taplio", founders=["Tibo (Thibault) Louis-Lucas"], product="Tweet Hunter / Taplio",
     domain="소셜미디어(X/LinkedIn) 성장 툴", one_liner="AI 보조 콘텐츠 작성·예약 기능으로 X/LinkedIn 퍼스널 브랜드 성장을 돕는 SaaS",
     team_size="소규모 팀 (TMAKER Studio)", region="프랑스",
     revenue="Tweet Hunter 12개월만에 ARR $1M 도달, 이후 약 $10M 규모로 SaaS 매각(exit) 보도",
     revenue_date="2022-2023", exit_status="acquired (매각, 정확한 인수자 미상세)",
     stack=["unknown"], ai_tools=["unknown"],
     founder_background="프랑스 출신 연쇄창업가, 빌드 인 퍼블릭 커뮤니티의 유명 인물",
     business_model="SaaS 구독",
     sources=["https://thebootstrappedfounder.com/thibault-louis-lucas-selling-a-10m-saas-and-building-another-one/"],
     confidence="medium"),

dict(id="lovable", founders=["Anton Osika", "Fabian Hedin"], product="Lovable (구 GPT Engineer)",
     domain="AI 바이브코딩 플랫폼", one_liner="자연어 프롬프트로 프론트엔드/백엔드/DB까지 자동 생성하는 스웨덴발 바이브코딩 유니콘",
     team_size="약 18~146명 (2025년초 18명 → 2026년초 146명으로 급성장)", region="스웨덴",
     revenue="출시 4개월만에 ARR 약 $30M; 2026-03 한 달간 매출 $100M 추가 보고; 2025-12 $330M 투자유치, 기업가치 $6.6B",
     revenue_date="2025-2026", exit_status="운영 중 (유니콘)",
     stack=["GPT 기반 자연어처리", "Supabase 연동"], ai_tools=["GPT 계열"],
     founder_background="Anton은 소프트웨어 개발자(YC 스타트업 CTO 경력), Fabian은 10세부터 창업 경험 있는 스웨덴 창업자",
     business_model="프리미엄/사용량 기반 SaaS",
     sources=["https://techcrunch.com/2026/03/11/lovable-says-it-added-100m-in-revenue-last-month-alone-with-just-146-employees/",
               "https://techcrunch.com/2025/12/18/vibe-coding-startup-lovable-raises-330m-at-a-6-6b-valuation/"],
     confidence="high"),

dict(id="bolt-new", founders=["Eric Simons"], product="Bolt.new (by StackBlitz)",
     domain="AI 바이브코딩 플랫폼", one_liner="브라우저 내에서 프롬프트로 풀스택 앱을 즉시 생성·배포하는 AI 코딩 에이전트",
     team_size="StackBlitz 소규모 코어팀", region="미국",
     revenue="출시 약 5개월만에 ARR 약 $40M 도달; 매출이 두 달만에 수천만 달러로 확대되며 $105.5M+ 투자유치",
     revenue_date="2024-2025", exit_status="운영 중",
     stack=["WebContainers(브라우저 내 실행환경)", "LLM 연동"], ai_tools=["unknown"],
     founder_background="기존 개발자도구 회사 StackBlitz의 창업자, Bolt.new는 피벗 제품",
     business_model="프리미엄/사용량 기반 SaaS",
     sources=["https://www.lennysnewsletter.com/p/inside-bolt-eric-simons"],
     confidence="medium"),

dict(id="cursor", founders=["Michael Truell", "외 3명"], product="Cursor (Anysphere)",
     domain="AI 코딩 IDE (개발자 도구)", one_liner="바이브코딩 시대에 널리 쓰이는 AI 기반 코드 에디터",
     team_size="MIT 졸업생 4인 창업팀에서 급성장", region="미국",
     revenue="2025-11 $2.3B 투자유치(기업가치 $29.3B); 2026-02 ARR $2B 도달 보도; 2026-06-16 SpaceX와 $60B 전액 주식교환 합병계약 체결(스타트업 인수 사상 최대) — 2026-08 현재 규제 승인 대기, 2026 3분기 클로징 예상",
     revenue_date="2025-2026", exit_status="acquired 예정 (SpaceX $60B 합병계약 체결, 클로징 미완료)",
     stack=["unknown"], ai_tools=["unknown"],
     founder_background="MIT 졸업생/중퇴자 4인, 현재 억만장자로 보도됨",
     business_model="개발자용 SaaS 구독",
     sources=["https://www.forbes.com/sites/rashishrivastava/2025/11/13/four-cofounders-of-popular-ai-coding-tool-cursor-are-now-billionaires/",
               "https://www.cnbc.com/2026/06/16/spacex-spcx-cursor-acquisition-ipo.html",
               "https://www.cbsnews.com/news/spacex-cursor-60-billion-ai-acquisition/",
               "https://www.forbes.com/sites/sandycarter/2026/06/16/spacex-buys-cursor-in-largest-startup-acquisition-ever-at-60-billion/"],
     confidence="high"),

dict(id="wave-ai", founders=["Josh Mohrer"], product="Wave AI", domain="AI 음성메모/회의 요약 앱",
     one_liner="대화를 녹음·전사·요약해주는 AI 음성노트 앱, 엔지니어링부터 고객지원까지 혼자 운영",
     team_size="1인 (솔로)", region="미국",
     revenue="연 매출 약 $7M, 순이익 약 $3M (2026-02 기준)", revenue_date="2026-02", exit_status="운영 중",
     stack=["Cursor", "Claude Code(Opus)", "Next.js", "Firebase"], ai_tools=["Whisper", "AssemblyAI", "Deepgram", "Claude"],
     founder_background="전 우버 뉴욕 GM, 헬스테크 스타트업 Levels 초기 멤버, 수학 전공, 정규 엔지니어링 배경 없이 바이브코딩으로 개발",
     business_model="구독형 SaaS (주/월/연 단위)",
     sources=["https://mixergy.com/interviews/the-7-million-vibe-coded-app/"],
     confidence="high"),

dict(id="ben-broca", founders=["Ben Broca"], product="(제품명 비공개, AI 비즈니스 관리 툴)",
     domain="AI 기반 1인 비즈니스 운영 도구", one_liner="이메일·코딩·고객응대·구독관리 등을 AI로 처리해 직원 없이 운영하는 SaaS",
     team_size="1인 (유일한 직원)", region="미국",
     revenue="연 매출 $10M 목표 궤도, 유료고객 10,000명; $30M 외부투자 유치",
     revenue_date="2025-2026", exit_status="운영 중",
     stack=["unknown"], ai_tools=["이메일/코딩/고객응대용 다양한 AI 툴(구체 미상세)"],
     founder_background="40세, 재택근무로 전량 운영, WSJ 최초 보도",
     business_model="구독형 SaaS",
     sources=["https://finance.yahoo.com/small-business/articles/ben-broca-raised-30-million-143000749.html"],
     confidence="medium"),

dict(id="deep-personality", founders=["Bryce Edwards", "Andrew Wilkinson"], product="Deep Personality",
     domain="AI 성격분석/궁합 서비스", one_liner="AI 기반 성격분석 및 커플 궁합 평가 서비스",
     team_size="2인", region="미국",
     revenue="출시 30일만에 $11,000 (2025-02 런칭, 기획~출시 6주)", revenue_date="2025-02", exit_status="운영 중",
     stack=["unknown"], ai_tools=["Claude/GPT-4 계열 추정"],
     founder_background="Bryce는 이전 회사 엑싯 경험, Andrew Wilkinson은 유명 연쇄창업가/투자자",
     business_model="프리미엄 (약 40% 무료, 전체 리포트는 유료)",
     sources=["https://www.indiehackers.com/post/from-0-to-11k-in-30-days-with-a-vibe-coded-ai-personality-analysis-b9ad81d534"],
     confidence="high"),

dict(id="dreamgf", founders=["Georgi Dimitrov"], product="DreamGF", domain="AI 컴패니언(가상 여자친구) 앱",
     one_liner="커스터마이징 가능한 AI 챗봇+이미지생성 가상 컴패니언 서비스", team_size="unknown", region="불가리아 추정",
     revenue="월 약 $120,000, 등록 유저 50만명, 유료고객 1만명, 출시 3개월만에 흑자전환",
     revenue_date="2025", exit_status="운영 중",
     stack=["Stable Diffusion", "ChatGPT 계열"], ai_tools=["Stable Diffusion", "ChatGPT"],
     founder_background="이전에 OnlyFans 크리에이터 에이전시 근무 경험", business_model="구독 티어제 (€10~€97/월, Patreon 결제)",
     sources=["https://sifted.eu/articles/ai-girlfriends"], confidence="medium"),

dict(id="appalchemy", founders=["Diego Roshardt"], product="AppAlchemy", domain="브라우저 기반 모바일 앱 빌더",
     one_liner="다운로드 없이 브라우저에서 네이티브 앱을 만드는 노코드 앱 빌더", team_size="1인", region="unknown",
     revenue="출시 12개월만에 MRR $10,000+", revenue_date="2024-2025", exit_status="운영 중",
     stack=["Next.js", "Supabase", "Claude Code", "Cursor", "React"], ai_tools=["Claude Code", "Cursor"],
     founder_background="독학(유튜브), 대학 때부터 프로젝트 진행, 스타트업 SWE로 잠깐 근무 후 풀타임 전환",
     business_model="구독형(월+할인 연간)",
     sources=["https://www.indiehackers.com/post/tech/launching-an-app-builder-in-2-weeks-and-hitting-10k-mrr-within-a-year-gRWT2S68TIQwMvb6Xxt4"],
     confidence="high"),

dict(id="launch-fast", founders=["Hasaam Bhatti"], product="Launch Fast", domain="아마존 셀러용 AI 리서치 툴",
     one_liner="아마존 셀러를 위한 상품 리서치/카탈로그관리/광고최적화 크롬 확장 프로그램",
     team_size="unknown (매우 소규모 추정)", region="unknown",
     revenue="런칭 30일 $10K → 60일 $17-18K → 90일 $21.8K → 현재 MRR $30K", revenue_date="2025", exit_status="운영 중",
     stack=["Cursor", "Next.js/React/TS", "Vercel", "Supabase", "Cloudflare", "Codex", "Claude Code"],
     ai_tools=["Codex", "Claude Code", "Cursor"],
     founder_background="비개발자, 아마존 FBA 셀러 출신, 이전에 10~12개 실패한 프로젝트 경험",
     business_model="티어형 구독($49/$89/$199, 무료 티어 없음)",
     sources=["https://www.indiehackers.com/post/tech/building-a-product-in-48-hours-and-hitting-30k-mrr-as-a-non-technical-founder-wWtWIH5tmwASUbxKaLT9"],
     confidence="high"),

dict(id="sleek-design", founders=["Mattia Pomelli", "외 2명(친구)"], product="Sleek (sleek.design)",
     domain="AI 모바일 UI 디자인 툴", one_liner="대화형으로 앱 UI를 디자인해주는 '바이브 디자인' AI 툴, 코딩/디자인 지식 불필요",
     team_size="3인", region="unknown",
     revenue="출시 6주만에 MRR $10,000, 유료마케팅 없이 달성", revenue_date="2024-2025", exit_status="운영 중",
     stack=["Next.js", "Supabase", "Vercel", "PostHog", "Stripe", "Resend"], ai_tools=["unknown"],
     founder_background="8년 코딩 경력, 팀원들과 이전에 디자인 툴 4개를 함께 만든 경험",
     business_model="AI 크레딧 기반 구독 티어, 제한적 무료 티어",
     sources=["https://www.indiehackers.com/post/tech/hitting-10k-mrr-in-six-weeks-with-an-ai-design-tool-pEvmU5qkWS6ny0AR9SUv"],
     confidence="high"),

dict(id="habit-pixel", founders=["Hirvesh Munogee"], product="Habit Pixel", domain="습관 트래커 앱",
     one_liner="픽셀아트 게이미피케이션 요소가 있는 크로스플랫폼 습관 트래커", team_size="1인", region="모리셔스",
     revenue="6개월 MRR $28 → 11월 $407 → 12월 $840 → 이듬해 1월 $1,000+ MRR", revenue_date="2025-06~2026-01",
     exit_status="운영 중", stack=["unknown"], ai_tools=["Claude Code"],
     founder_background="독학 개발자, 본인의 습관형성 어려움을 해결하려고 제작",
     business_model="프리미엄 ($4.99/월 또는 $29.99/년, PPP 가격, 블프 라이프타임 프로모션)",
     sources=["https://www.indiehackers.com/post/from-0-to-1k-mrr-in-8-months-bootstrapping-habit-pixel-as-a-solo-dev-684b6c056d"],
     confidence="high"),

dict(id="subscribr", founders=["Gil Hildebrand", "(18개월 후 공동창업자 합류)"], product="Subscribr",
     domain="유튜버용 AI 콘텐츠 기획 툴", one_liner="유튜브 크리에이터의 영상 아이디어/패키징/스크립트 기획을 돕는 AI 툴",
     team_size="처음엔 1인, 이후 2인", region="unknown",
     revenue="사전판매 $20K → 퍼블릭 런칭 100일만에 MRR $10K → 현재 MRR $62K+ → 1년차 $500K+, 2년차 $1M+ 목표",
     revenue_date="2024-2025", exit_status="운영 중",
     stack=["Laravel", "Livewire", "Laravel Horizon", "단일 DigitalOcean droplet"], ai_tools=["unknown"],
     founder_background="25년 이상 코딩 경력, 세스 고딘의 회사 Squidoo 전 CTO(3인 엔지니어링팀으로 연매출 $10M 달성 경험), VC 투자받은 크립토 스타트업 경력",
     business_model="SaaS 구독($49+/월), 라이프타임딜/AppSumo, 제휴 프로그램",
     sources=["https://www.indiehackers.com/post/tech/hitting-125k-mrr-as-a-solo-founder-by-doubling-down-on-the-right-segment-c4o2Tfs6mjdpip5yZhaO"],
     confidence="medium"),

dict(id="samuel-rondot-portfolio", founders=["Samuel Rondot"], product="StoryShort.ai / UseArtemis / Capacity.so",
     domain="SaaS 포트폴리오(AI 숏폼영상생성/아웃리치툴/AI코딩툴)",
     one_liner="검증된 서비스를 벤치마킹해 복제·개선하는 방식으로 여러 SaaS를 운영하는 1인 포트폴리오",
     team_size="대부분 1인 (Capacity는 고교 동창과 공동창업)", region="프랑스 추정",
     revenue="StoryShort ~$20K/월, UseArtemis ~$5-15K/월, Capacity ~$0.9-3K/월, 합계 월 $28-35K; 이전 제품 MathPlanner는 월 $30K 달성",
     revenue_date="2025-12", exit_status="운영 중",
     stack=["Next.js", "Node.js", "MongoDB", "Vercel/AWS"], ai_tools=["unknown"],
     founder_background="전직 안경사(의료계), 유튜브 독학으로 코딩 습득, 인스타그램 자동화 서비스 운영 후 SaaS로 전환",
     business_model="SaaS 구독",
     sources=["https://www.indiehackers.com/post/tech/learning-to-code-and-building-a-28k-mo-portfolio-of-saas-products-OA5p18fXtvHGxP9xTAwG",
               "https://maily.so/josh/posts/5xrx6lnqr2v"],
     confidence="medium"),

dict(id="lancer", founders=["Ivan Nedelkovski"], product="Lancer", domain="프리랜서용 AI 리드젠 에이전트",
     one_liner="Upwork에서 프리랜서의 리드 발굴과 제안서 제출을 자동화하는 AI 에이전트", team_size="2인", region="unknown",
     revenue="런칭 60일만에 MRR $10K → $20K → 현재 $25K+/월", revenue_date="2025", exit_status="운영 중",
     stack=["GCP", "Firestore", "Hetzner", "TypeScript/Node/Next.js", "Elasticsearch", "Openrouter"],
     ai_tools=["Openrouter(AI 라우팅)"],
     founder_background="대학 두 번 중퇴, 개발 컨설팅 회사(MVP Masters)를 15명/7자리수 매출 규모로 키운 뒤 2025년 매각한 경험",
     business_model="구독 티어(Pay-per-Lead $149/월, Unlimited $499/월) + 제휴 코칭",
     sources=["https://www.indiehackers.com/post/tech/exiting-his-agency-and-hitting-10k-mrr-within-60-days-of-launching-his-saas-sTo5m9qfhxXbruvhBIyH"],
     confidence="high"),

dict(id="creator-buddy", founders=["Alex Finn"], product="Creator Buddy", domain="AI 콘텐츠 생성 툴 (X/Twitter)",
     one_liner="X(트위터) 게시물을 분석해 개인화된 콘텐츠를 생성해주는 AI 도구", team_size="1인 (직원 0명)", region="unknown",
     revenue="10개월만에 ARR $300K", revenue_date="2025", exit_status="운영 중",
     stack=["Next.js", "Vercel", "Supabase", "Claude Code"], ai_tools=["Claude Code"],
     founder_background="비개발자 출신", business_model="SaaS + 유료 '바이브코딩 아카데미' + 뉴스레터",
     sources=["https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="medium"),

dict(id="vibed-agents", founders=["Paulius (@0xPaulius)"], product="Vibed Agents", domain="자율 코딩 에이전트 플랫폼",
     one_liner="자율 코딩 에이전트를 배포해 앱을 만들어주는 플랫폼", team_size="1인", region="unknown",
     revenue="MRR $9K, 누적 $100K+, 10개 이상 앱에 걸쳐 유저 3만명+", revenue_date="2025", exit_status="운영 중",
     stack=["Claude Code", "MCP"], ai_tools=["Claude Code"],
     founder_background="런칭 9개월 전까지 커밋 경험 없는 비개발자", business_model="플랫폼/SaaS",
     sources=["https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="medium"),

dict(id="plinq", founders=["Sabrine Matos"], product="Plinq", domain="데이팅 안전 앱",
     one_liner="상대방을 공개 범죄기록과 대조 확인해주는 데이팅 안전 앱(위험도 평가, 패닉버튼 등)",
     team_size="unknown (프리시드 투자 유치 중)", region="브라질",
     revenue="ARR $456,000, 유저 1만명+, 45일만에 개발", revenue_date="2025", exit_status="운영 중",
     stack=["Lovable"], ai_tools=["Lovable"],
     founder_background="브라질의 그로스마케터, 코딩 경험 전무", business_model="구독/건당 확인 수수료",
     sources=["https://everydayaiblog.com/vibe-coded-apps-real-revenue-users/"], confidence="medium"),

dict(id="klar", founders=["Isabel Storgårds", "Andreas Melander", "Eric Götborg"], product="Klar (구 Tentaklar)", domain="AI 교육 플랫폼",
     one_liner="웁살라대 학생 3인이 Lovable로 만든 AI 학습 에이전트", team_size="3인 (웁살라대 학생, 2인은 학업 중단 후 풀타임)", region="스웨덴 (웁살라)",
     revenue="출시 30일만에 ARR $130,000 (창업자 본인 LinkedIn 공개), 인수 제안 받았으나 거절", revenue_date="2026-02", exit_status="운영 중(인수 제안 거절)",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="경영학 전공 대학생 3인 공동창업 (비개발자)",
     business_model="AI 교육 플랫폼 구독",
     sources=["https://www.linkedin.com/posts/isabel-storg%C3%A5rds-298a42228_in-january-we-launched-tentaklar-from-a-activity-7445502521768595456-Sh8P",
              "https://www.uu.se/en/news/2026/2026-01-16-from-student-challenges-to-a-study-platform",
              "https://klarlabs.ai",
              "https://www.arr.club/klar/klar-arr-hit-130k-within-30-days-of-launch-built-with-lovable"], confidence="high"),

dict(id="quicktables", founders=["Jaleel Miles", "Hussein Hanses", "Morten Gjesdal Bech", "Zanyar Rahem"], product="QuickTables", domain="레스토랑 관리 플랫폼",
     one_liner="말뫼의 20대 팀이 Lovable로 만든 레스토랑 운영 SaaS — 11개월만에 exit", team_size="창업팀 4인 내외 + 채용 13명 (창업자 명단은 출처별로 상이)", region="스웨덴 (말뫼)",
     revenue="출시 8주만에 ARR €120,000 (창업자 exit 포스트), 2026-03 전략적 인수자에 매각(금액 비공개)", revenue_date="2025", exit_status="acquired (2026-03)",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="영업 출신 창업자(Jaleel Miles) + CTO/CPO(Zanyar Rahem), €1,000으로 시작",
     business_model="레스토랑 운영 소프트웨어 구독",
     sources=["https://www.linkedin.com/posts/jaleel-miles-78b81a255_today-we-have-exited-quicktables-a-software-activity-7443346236000116736-ZgvV",
              "https://oresundstartups.com/malmo-startup-quicktables-achieves-e90k-arr-in-just-two-months-using-lovable-platform/",
              "https://aivibecheck.substack.com/p/the-vibe-check-6-building-apps-at"], confidence="high"),

dict(id="appbilchat", founders=["박현중"], product="앱빌챗", domain="AI 앱 개발 대행 SaaS (한국)",
     one_liner="채팅으로 아이디어를 설명하면 AI PM이 요구사항을 구조화하고 AI+엔지니어 협업으로 앱 개발부터 출시·서버운영까지 대행",
     team_size="unknown (법인, AI+인간 엔지니어 협업 구조)", region="한국",
     revenue="unknown (법인 설립 3개월만에 프리시드 투자유치, 4개월만에 TIPS 선정)", revenue_date="2026", exit_status="운영 중",
     stack=["자체 AI PM + AI/엔지니어 협업 개발"], ai_tools=["unknown"],
     founder_background="대학 시절부터 프리미엄 배송·리셀 플랫폼 등 연쇄창업 및 엑싯 경험, 2023년 오픈소스 LLM 공개 이후 AI 개발 확신을 갖게 됨",
     business_model="구독형 앱 개발 대행 서비스(B2B/B2C)",
     sources=["https://zdnet.co.kr/view/?no=20260617083532"], confidence="medium"),

dict(id="gendy", founders=["어보브테크 공동창업팀"], product="젠디(Gendy)", domain="AI 컴패니언 상담 콘텐츠 (한국)",
     one_liner="사주·헤어·심리·타로 등을 다루는 AI 컴패니언 상담 콘텐츠 플랫폼", team_size="unknown (소규모 추정)", region="한국",
     revenue="런칭 6개월만에 월 1억원(이전 월 3천→5천만원 단계 거침), 회원 4만명, 유료전환율 약 30%",
     revenue_date="2026", exit_status="운영 중",
     stack=["GPT Pro", "Cursor", "Perplexity", "LLM 챗봇", "스레드 API 자동화 마케팅"], ai_tools=["GPT Pro", "Cursor", "Perplexity"],
     founder_background="2020년 마스크 알리미 서비스 개발 경험, 블록체인 B2B 사업(연매출 30억) 경력",
     business_model="앱 내 AI 상담 콘텐츠 유료 판매",
     sources=["https://maily.so/unsexybusinesskr/posts/92zew8j7zep"], confidence="medium"),

dict(id="relic-ai", founders=["뤼튼/보이저엑스 출신 공동창업자 2인"], product="릴리스 AI (Relic AI)", domain="AI 유튜브 요약 서비스 (한국)",
     one_liner="유튜브 영상을 한국어로 요약해주는 AI 서비스", team_size="2인", region="한국",
     revenue="출시 6개월 시점 월 1,000만원, 사용자 14만명 이상", revenue_date="2025-2026", exit_status="운영 중",
     stack=["LLM 기반 요약"], ai_tools=["unknown"],
     founder_background="뤼튼(Wrtn), 보이저엑스 출신 개발자", business_model="페이드마케팅·투자 없이 유기적 성장(구독/이용료 추정)",
     sources=["https://eopla.net/magazines/15235", "https://disquiet.io/articles/W9sy71"], confidence="medium"),

dict(id="trend-widget", founders=["맥그리 (본명 한길웅, 법인 (주)코코큐큐)"], product="실검 위젯", domain="실시간 검색어/뉴스 위젯 앱 (한국)",
     one_liner="홈화면 위젯으로 실시간 검색어와 AI 요약 뉴스 제공 — KR 앱스토어 뉴스 카테고리 1위", team_size="1인 (법인 운영)", region="한국 (성남)",
     revenue="비공개 (인앱 광고 + 구독 Pro 월 ₩8,800 운영 중; 다운로드 2만+·DAU 4,000+은 자진신고)", revenue_date="2025-2026", exit_status="운영 중",
     stack=["AWS Kiro", "Cursor"], ai_tools=["AWS Kiro", "Cursor"],
     founder_background="개발경력 8~9년의 현직/전직 개발자",
     business_model="인앱 광고 + 구독 (토스 미니앱 연동 계획)",
     sources=["https://www.gpters.org/dev/post/service-created-vibe-coding-x5dpT0BzKfnigQG",
              "https://apps.apple.com/kr/app/id6749870074",
              "https://play.google.com/store/apps/details?id=com.coincurator.homenow",
              "https://www.trendwidget.app/",
              "http://www.mediadale.com/news/articleView.html?idxno=254655"], confidence="high"),

dict(id="my-askai", founders=["Mike Heap", "Alex Rainey"], product="My AskAI", domain="AI 고객상담 챗봇",
     one_liner="웹사이트 콘텐츠를 학습해 응답하는 AI 고객지원 에이전트", team_size="2인 (2025년 현재도 2인 유지, 등록 유저 4만+)",
     region="unknown", revenue="$40K MRR (~$500K ARR, 2025-07 창업자 인터뷰; 2023년 $14K MRR·유료 약 300명)", revenue_date="2025-07", exit_status="운영 중",
     stack=["Bubble(약 80%)", "Python", "OpenAI API"], ai_tools=["OpenAI API"],
     founder_background="비개발자 출신 2인 (2023년 초 출시 후 고객지원 에이전트로 피벗)", business_model="SaaS 구독 (AI 고객지원 에이전트, 월 75K+ 상담 처리)",
     sources=["https://www.indiehackers.com/post/tech/bootstrapping-to-40k-mrr-after-his-vc-backed-startup-failed-LF1CwRs1vL3oVLcuoIoE",
              "https://www.indiehackers.com/post/making-14k-mrr-with-a-custom-chatgpt-tool-9f25e8fe11",
              "https://bubble.io/blog/myaskai/"], confidence="high"),

# flexiple 제거 (2026-08-10): 검증 결과 2016년 창업·3인 공동창업·순수 노코드(2016-2021) 사례로
# AI 코딩 툴 시대(2023~) 아카이브 스코프에 부합하지 않음. 원출처의 "1인 창업" 주장도 오류.

dict(id="formula-bot", founders=["David Bressler"], product="Formula Bot", domain="AI 엑셀/SQL 함수 생성 → AI 데이터 분석 플랫폼",
     one_liner="엑셀 함수 AI 생성으로 시작해 AI 데이터 분석 플랫폼으로 확장한 1인 SaaS", team_size="1인 (파트타임 계약 Bubble 개발자 2명 활용)", region="미국 (올랜도)",
     revenue="$500K ARR (2024), $42K+ MRR (2025, 창업자 인터뷰; 2023년 월 $22-25K)", revenue_date="2024-2025", exit_status="운영 중",
     stack=["Bubble(노코드)", "OpenAI API"], ai_tools=["OpenAI API", "Gemini"],
     founder_background="마케팅 애널리틱스 12년+ 디렉터 출신 비개발자, 육아휴직 중 주말에 MVP 제작(2022-08 출시)", business_model="구독료 기반 SaaS (누적 유저 100만+)",
     sources=["https://www.starterstory.com/stories/excelformulabot",
              "https://www.indiehackers.com/post/tech/getting-serious-about-marketing-after-hitting-500k-arr-8XGnzrxG1neA3jy37x2D",
              "https://bubble.io/blog/formula-bot/"], confidence="high"),

dict(id="ai-coding-consultancy", founders=["Prajwal Tomar"], product="Ignyt Labs / AI MVP Builders", domain="AI 활용 MVP 개발 에이전시",
     one_liner="AI 툴로 21일만에 클라이언트 MVP를 만들어주는 에이전시 (최단 14일)", team_size="2인 이상 (에이전시, 규모 비공개)", region="인도",
     revenue="unknown (40+ MVP 납품 — 본인 사이트 기준; MVP 개발 월 $5,497부터)", revenue_date="unknown", exit_status="운영 중",
     stack=["Lovable", "Cursor", "Claude Code", "Next.js", "Supabase"], ai_tools=["Lovable", "Cursor", "Claude Code"],
     founder_background="unknown", business_model="컨설팅/에이전시 + 유료 커뮤니티(AI MVP Builders)",
     sources=["https://www.ignytlabs.com/",
              "https://x.com/PrajwalTomar_",
              "https://in.linkedin.com/in/prajwal-tomar-9472081a5",
              "https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="medium"),

dict(id="anything", founders=["Dhruv Amin", "Marcus Lowe"], product="Anything", domain="AI 코딩 플랫폼",
     one_liner="AI 코딩 플랫폼 스타트업(엔드유저 제품이 아닌 플랫폼 자체), 출시 2주만에 ARR $2M",
     team_size="unknown", region="미국",
     revenue="출시 2주만에 ARR $2M, 기업가치 $100M", revenue_date="2025-09", exit_status="운영 중",
     stack=["unknown"], ai_tools=["unknown"], founder_background="구글 출신 공동창업자들",
     business_model="AI 코딩 플랫폼 SaaS",
     sources=["https://techcrunch.com/2025/09/29/vibe-coding-startup-anything-nabs-a-100m-valuation-after-hitting-2m-arr-in-its-first-two-weeks/"],
     confidence="medium"),

dict(id="simon-berg-portfolio", founders=["Simon Berg"], product="Frame My Home / Spellbound (MSH Studios)",
     domain="AI 인테리어 아트 프린트 / AI 교육 앱", one_liner="집·반려동물 사진을 AI 아트 액자로, 철자 학습지를 인터랙티브 게임으로 변환",
     team_size="제품당 1~2인", region="영국",
     revenue="신규 벤처 매출 비공개 (이전 회사 Ceros는 연 매출 약 $60M까지 성장 후 지분 58% 매각)", revenue_date="2025-2026",
     exit_status="운영 중", stack=["Bolt.new", "Stripe", "11 Labs", "AI 에이전트"], ai_tools=["Bolt.new"],
     founder_background="17세에 영국 크리에이티브 에이전시 사환으로 시작, Ceros를 12년간 $30K에서 $60M ARR로 키운 뒤 2020년 매각, 현재 AI 인큐베이터 MSH Studios 운영",
     business_model="Frame My Home=주문제작 프린트, Spellbound=교육 구독",
     sources=["https://bolt.new/blog/how-ceo-built-two-businesses-with-bolt"], confidence="high"),

# ── 2026-08-10 정기 리서치 1회차 반영분 (data/candidates/ 검증 리포트 참조) ──

dict(id="kleo", founders=["Cameron Trew", "Jake Ward", "Lara Acosta", "Rob Hoffman"], product="Kleo (kleo.so)",
     domain="LinkedIn 콘텐츠 제작 툴",
     one_liner="LinkedIn 크리에이터 팀이 Claude Code로 재구축한 콘텐츠 툴 — 재런칭 3개월 만에 $62K MRR",
     team_size="4인 (사이트 표기는 공동창업자 3인)", region="영국",
     revenue="$62K MRR (2025-12 창업자 인터뷰; 자매품 Mentions.so 합산 시 월 $82K)", revenue_date="2025-12", exit_status="운영 중",
     stack=["Claude Code", "Claude API", "Claude Vision"], ai_tools=["Claude Code"],
     founder_background="개발자 1인(Cameron Trew, 약 6년 경력) + 대형 오디언스 보유 LinkedIn 크리에이터들",
     business_model="SaaS 구독 (무료 크롬 확장 6만 유저 → LinkedIn C&D로 폐쇄 → 유료 웹앱 재런칭)",
     sources=["https://www.indiehackers.com/post/tech/from-0-to-62k-mrr-in-three-months-mUPVSYOlJAC2iogGK7d4",
              "https://camerontrew.com/", "https://kleo.so/"], confidence="medium"),

dict(id="superx", founders=["Rob Hallam", "Tibo Louis-Lucas"], product="SuperX (superx.so)",
     domain="X(트위터) 성장 툴",
     one_liner="5번 실패한 창업자가 Claude Code로 재구축한 X 성장 툴 — 약 7개월 만에 $23K MRR",
     team_size="2인", region="영국(Rob) / 프랑스(Tibo)",
     revenue="$23K MRR, 유료 고객 약 650명·$39/mo (2026-02 창업자 인터뷰; 6개월 시점 본인 트윗은 $17K MRR)",
     revenue_date="2026-02", exit_status="운영 중",
     stack=["Claude Code", "OpenAI API", "Claude API"], ai_tools=["Claude Code"],
     founder_background="Rob Hallam은 5회 실패 후 합류한 성장 담당, Tibo Louis-Lucas는 Tweet Hunter/Taplio exit 연쇄창업자 — 2024년 인수한 크롬 확장을 재구축",
     business_model="SaaS 구독",
     sources=["https://www.indiehackers.com/post/tech/hitting-23k-mrr-in-six-months-after-five-failures-4d64o9ev4AXXhX9ogHQQ",
              "https://x.com/robj3d3/status/2013931593371439279", "https://www.tmaker.io/"], confidence="medium"),

dict(id="imaginary-space", founders=["Harry Mckay Roper"], product="Imaginary Space",
     domain="Lovable 전문 개발 에이전시",
     one_liner="Lovable 전문 에이전시로 월 $100K 매출", team_size="unknown (에이전시)", region="unknown",
     revenue="월 $100K, 연말까지 $1.2M 페이스", revenue_date="2025-2026", exit_status="운영 중",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="unknown",
     business_model="에이전시 (클라이언트 앱 개발 대행)",
     sources=["https://lovable.dev/video/he-makes-100kmonth-with-his-lovable-agency",
              "https://www.linkedin.com/in/harry-mckay-roper-434a8a130/",
              "https://www.nocode.mba/articles/lovable-agency-ai-coding"], confidence="medium"),

dict(id="lumoo", founders=["Henrik Skagerlind Fasth", "Peter Thörngren"], product="Lumoo",
     domain="AI 패션 콘텐츠 플랫폼",
     one_liner="Lovable로 만든 패션 브랜드용 AI 콘텐츠 플랫폼 — 9개월 만에 €700K ARR (투자자 발 수치)",
     team_size="2인", region="스웨덴",
     revenue="€700K ARR/9개월 — 발화자가 Lovable CEO(SEK 6M 엔젤 투자자)뿐, 창업자 본인 발화 미확보",
     revenue_date="2025", exit_status="운영 중",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="unknown",
     business_model="B2B SaaS (노르딕 패션 브랜드 15+ 고객)",
     sources=["https://lovable.dev/blog/lumoo-ai-fashion-platform",
              "https://x.com/antonosika/status/1975229636910203199",
              "https://tech.eu/2025/12/05/lovable-built-lumoo-gets-funding-from-lovable-ceo/"], confidence="low"),

dict(id="stoppr", founders=["David Attias"], product="STOPPR 외 앱 포트폴리오",
     domain="모바일 앱 포트폴리오 (설탕 끊기 등 습관 개선)",
     one_liner="Cursor 바이브코딩으로 1년 만에 월 $10K 앱 포트폴리오 — 주력 앱이 Apple 계정 종료로 퇴출된 플랫폼 리스크 사례",
     team_size="1인 (Adapty devrel 겸직)", region="프랑스",
     revenue="앱 매출 월 ~$10.5K (2026-05 자가보고, 정점 $12-14K/mo) — 2025-11 주력 앱 STOPPR 앱스토어 퇴출 후 하락 추세",
     revenue_date="2026-05", exit_status="주력 앱 퇴출 후 재건 중",
     stack=["Cursor", "Claude", "Figma MCP"], ai_tools=["Cursor", "Claude"],
     founder_background="파리 CS 스쿨 졸업, Criteo TAM·트레이딩 알고리즘 프리랜서 7년",
     business_model="앱 구독 (QUITTR 모델을 설탕 끊기 니치에 적용)",
     sources=["https://www.indiehackers.com/post/tech/from-zero-to-10k-mo-app-portfolio-in-a-year-71h2PPGYn1VnPOkj9qi6",
              "https://www.whatsthe.app/com.stoppr.app",
              "https://x.com/david_attisaas/status/1998081954856513893"], confidence="medium"),

dict(id="ninjapear", founders=["Steven Goh"], product="NinjaPear",
     domain="B2B 데이터 엔리치먼트 API",
     one_liner="이전 회사가 소송으로 문을 닫은 뒤 Claude Code로 2주 만에 만들어 재출발한 데이터 엔리치먼트 API",
     team_size="1인 (채용 계획 없음을 본인 명시)",
     region="싱가포르",
     revenue="월 총매출(gross) $15,000 초과 — 2026-05 실적, 본인 블로그(2026-06-30) \"15K revenue last mo\" 및 인터뷰 \"We did over $15k in gross revenue last month\". 같은 글에 \"more than 10K in the last 2 months\"도 병존해 월 $10K~15K대 범위. 본인 ARR 발화는 2026-03 $66K(실적)와 $1M(목표)뿐",
     revenue_date="2026-05", exit_status="운영 중 (본인 흑자 발화)",
     stack=["자택 하드웨어 Kubernetes (Intel NUC + Framework)", "OpenRouter", "Xero"],
     ai_tools=["Claude Code", "Codex"],
     founder_background="연쇄창업가. 이전 회사 Proxycurl(SWE 과반 포함 약 60인)을 ARR $10M까지 키웠으나 2025-01 LinkedIn 소송 후 2025-07 서비스 종료. 이후 '경쟁사에 매각'이라 발화했으나 본인의 종료 공지 및 독립 보도는 셧다운으로만 기술 — 매각은 미확인",
     business_model="하이브리드 — 구독 플랜 + PAYG 크레딧 (3일·10크레딧 무료체험)",
     sources=["https://www.indiehackers.com/post/MMWkpCaClOB6wVgbuPI7",
              "https://nubela.co/blog/how-im-building-a-1m-arr-venture-with-ai-as-a-bootstrapped-solo-founder-15k-revenue-last-mo-10m-last-exit-w-proxycurl/",
              "https://nubela.co/blog/introducing-ninjapear-2026-customer-listing-api/",
              "https://nubela.co/blog/introducing-person-profile-endpoint-also-1000-users-66k-arr/"],
     confidence="high"),

dict(id="jonathan-geiger-portfolio",
     founders=["Jonathan Geiger", "Yoav Mendelson (PostPeer 공동창업자)"],
     product="PostPeer / SocialKit(2026-08 매각)",
     domain="개발자용 소셜미디어 데이터·게시 API",
     one_liner="3년간 사이드로 시도하다 5·6번째 제품에서 트랙션을 얻고 연쇄 매각으로 이어간 개발자 API 포트폴리오",
     team_size="SocialKit 1인 / PostPeer 2인 공동창업", region="이스라엘",
     revenue="2026-07 월매출 $7,740 (PostPeer $3,998 + SocialKit $3,742) — 창업자 본인 2026-08-01 X 결산, 전업 전환 후 첫 만월. 2026-08-06 SocialKit 매각으로 이후 잔존 제품은 PostPeer 단독. PostPeer MRR은 본인 $2,661/활성구독 112(2026-07-29)와 Polar API 검증 $1,989/활성구독 79(2026-08-11)가 불일치",
     revenue_date="2026-07",
     exit_status="부분 exit — SocialKit 2026-08-06 매각(매각가 비공개). 과거 exit: LectureKit $7K, CaptureKit $15K",
     stack=["unknown"], ai_tools=["Claude"],
     founder_background="3년간 사이드 프로젝트를 반복하다 2026-07 전업 전환. 연쇄 exit 3건 — LectureKit $7K, CaptureKit $15K(런칭 2.5개월 후, 당시 MRR $127), SocialKit(2026-08, 금액 비공개)",
     business_model="API 사용량 크레딧 구독 + 일회성 크레딧 팩",
     sources=["https://www.indiehackers.com/post/5kZRj2Lln7jO7nVVoYFP",
              "https://x.com/JonathanGeige18",
              "https://www.postpeer.dev/about",
              "https://trustmrr.com/startup/postpeer"],
     confidence="medium"),

dict(id="sergiu-chiriac-portfolio", founders=["Sergiu Chiriac"],
     product="AI Directories / TransClipper / BrandReply / ColdConvert",
     domain="인디메이커 대상 제품 등록·유통 자동화 툴",
     one_liner="자기가 쓰려고 만든 디렉터리 등록 자동화 툴을 포트폴리오로 확장한 1인 메이커",
     team_size="1인 (공동창업자 없음)", region="포르투갈 리스본",
     revenue="본인 일반진술 \"Across all my projects, I typically generate over $10k/mo\" (IH 2026-08-06). 2026-07 본인 결산 총 $20,500 — 항목: AI Directories $9,771 / 제휴 $7,900 / 제품명 비공개 앱 $2,500 / TransClipper $50 (항목 합 $20,221로 본인 표기 총액과 $279 불일치). 일회성 구매 중심이라 MRR 아님",
     revenue_date="2026-07", exit_status="운영 중",
     stack=["Next.js", "MongoDB", "Prisma", "Tailwind", "Vercel", "Coolify", "Stripe", "Resend"],
     ai_tools=["Cursor"],
     founder_background="본인이 겪은 제품 등록 문제를 풀려고 만든 툴에서 출발한 1인 메이커. 몰도바 출생, 포르투갈 20년 거주",
     business_model="일회성 구매 중심 (디렉터리 등록 Starter $99 / Pro $149 / Premium $199) + 제휴 수입(2026-07 기준 38.5%) + 컨설팅 판매",
     sources=["https://www.indiehackers.com/post/1r8AaZOjxXZSB5MMAhG5",
              "https://x.com/s_chiriac/status/2083116055854002519",
              "https://www.aidirectori.es/about-us",
              "https://www.sergiuchiriac.com/"],
     confidence="medium"),

dict(id="rightblogger", founders=["Ryan Robinson", "Andy Feliciotti"], product="RightBlogger",
     domain="블로거·콘텐츠 마케터용 AI 도구 묶음",
     one_liner="12년 축적한 블로그 오디언스(월 독자 50만) 위에 얹어 출시 첫 주에 MRR $2K를 낸 콘텐츠 SaaS",
     team_size="3인 (창업 2인: Ryan 유통·영업 / Andy 개발, 이후 운영 총괄 1인 합류)",
     region="미국",
     revenue="약 $350K/년 — 본인 발화 \"We're currently at $350k ARR\" (2026-07-01). 2023년 출시 첫 주 본인 발화 \"We got our first $2k MRR during week one\"",
     revenue_date="2026-07", exit_status="운영 중",
     stack=["Next.js", "React", "Node.js", "PostgreSQL"],
     ai_tools=["Claude Code"],
     founder_background="Ryan Robinson은 ryrob.com 월 독자 약 50만·이메일 구독 30만을 12년 축적한 블로거(Forbes·Entrepreneur 기고), Andy Feliciotti는 10년+ 경력 실무 개발자. 선행 오디언스 위에 얹은 출시로 첫 주에 이미 MRR $2K",
     business_model="구독 SaaS 3단계 (Solo $59 / Pro $89 / Agency $299, 2026-08 관측)",
     sources=["https://www.indiehackers.com/post/KxUy5Zjfn1hJTTGYrl47",
              "https://drawne.com/claude-code-commands/",
              "https://ryan.biz/",
              "https://www.cloudflare.com/case-studies/rightblogger/"],
     confidence="medium"),

dict(id="leadverse", founders=["Jakub Mužík"], product="Leadverse",
     domain="소셜 리드 발굴 SaaS (Reddit·X 등)",
     one_liner="본업·프리랜스·육아를 병행하며 1인으로 만든 소셜 리드 발굴 도구 — Reddit API 회수 사건을 겪은 플랫폼 리스크 표본",
     team_size="1인", region="체코 프라하",
     revenue="MRR $3.3K / 누적 총매출(gross) $20K 초과 / 유료 고객 130명 이상 — 본인 발화(2026-08-11). 유료 130명 중 약 30명이 가격을 스스로 조정하는 커스텀 플랜. 2026-01 시점 MRR $1,100+",
     revenue_date="2026-08-11 (발화 시점 — 측정 시점은 2026-07 중순 추정)",
     exit_status="운영 중 — 2026-07-16경 Reddit이 API 키 4개를 예고 없이 전량 회수해 핵심 기능이 정지한 이력(당시 유료 130명+). 복구 방법 본인 발화는 미확보",
     stack=["React", "Supabase", "Stripe", "Resend"], ai_tools=["unknown"],
     founder_background="본업(MSD Salesforce 개발자) + 프리랜스 + 육아 병행 사이드 프로젝트. 체코생명과학대 정보학 석사",
     business_model="구독 — 최초 €9/€14(EUR)로 시작해 약 1개월 후 USD 전환, 현재 Explorer $19 / Founder $29 / Business $39 + 커스텀. 7일 무료체험",
     sources=["https://www.indiehackers.com/post/U9btJ44RYRcAaukCqHoj",
              "https://x.com/jakubmuzzik",
              "https://cz.linkedin.com/in/jakub-muzik",
              "https://www.capterra.com/p/10040556/Leadverse/"],
     confidence="medium"),

dict(id="ramsri-portfolio",
     founders=["Ramsri Goutham Golla", "Sanjeev NC", "Nico Botha (Supermeme.ai 공동창업 2인)"],
     product="Questgen.ai / AiArtist.io / Supermeme.ai (포트폴리오)",
     domain="AI 문제생성·이미지생성·밈생성 SaaS 포트폴리오",
     one_liner="정규직 데이터 사이언티스트가 겸업으로 운영하는 AI SaaS 3종 — 2022년 기원 제품을 Claude Code로 유지·확장하는 유형",
     team_size="혼합 — Questgen·AiArtist는 1인 단독, Supermeme.ai는 3인 공동창업. 직원 없음",
     region="인도 하이데라바드",
     revenue="포트폴리오 3종 합산 월 $6,000~$7,000 MRR — 본인 발화 \"Currently, they hover between $6k and $7k MRR\" (2026-07-30). 분해 가능한 수치는 Questgen 누적 $150K USD(4년). 2025년 정점 총 ARR $100K에서 하락",
     revenue_date="2026-07", exit_status="운영 중",
     stack=["NextJS", "Supabase"], ai_tools=["Claude Code"],
     founder_background="인도 하이데라바드 소재. 정규직 데이터 사이언티스트(Knownwell Lead Data Scientist) 겸 인디메이커. Questgen 첫 버전은 Bubble 노코드로 제작",
     business_model="Questgen·Supermeme 구독 (스타터 $10~15, 상위 $50, 연 40% 할인) / AiArtist는 $99 일회성 연간 패스",
     sources=["https://www.indiehackers.com/post/quOo7AXtrGlePopsGslc",
              "https://ramsrigoutham.medium.com/the-story-of-my-4k-mrr-solo-saas-questgen-ai-41f68f4f6a5a",
              "https://supermeme.ai/team",
              "https://github.com/ramsrigouthamg"],
     confidence="medium"),

dict(id="bazzly",
     founders=["Filip Panoski", "실명 미공개 파트너 1인 (지분 50%, MRR $1K 시점 합류)"],
     product="Bazzly",
     domain="마케팅/그로스 SaaS — Reddit 리드 발굴·댓글·DM 자동화 (B2B)",
     one_liner="SaaS 4~5건 실패 후 퇴사해 12개월 만에 월 $7.5K에 도달 — 도중 50% 파트너 1인 합류",
     team_size="2인 (창업 시점 1인 → MRR $1K 시점 합류한 50% 파트너 1인, 실명 미공개). 본인 발화 \"being solo was my biggest bottleneck\"",
     region="북마케도니아 스코페",
     revenue="2026-07 기준 월 $7.5K — 본인 원문 \"I grew it from $0 to $7.5k/mo in 12 months. MRR is $5k, but one-time payments within the platform drive $2.5k in monthly expansion revenue.\" 결제사 검증 대조: Stripe API 기준 MRR $6,781 / 활성구독 62 / 누적 $27,656 / 지난 30일 $8,614 (TrustMRR, 2026-08-12). 본인 마일스톤 시계열: 2025-06 $0 → 2026-03 $1K 돌파 → 2026-05경 $5K",
     revenue_date="2026-07", exit_status="운영 중",
     stack=["Next.js", "Supabase", "Node.js", "React"], ai_tools=["unknown"],
     founder_background="기술 창업자(Java·React 개발자 배경). SaaS 제품 4~5건 실패 후 퇴사. 동일 법인(Meeteo Labs, LLC)으로 두 번째 제품 SaaSCurate도 운영 중",
     business_model="$99/월 단일 플랜(100 크레딧 포함) + 크레딧 충전·추가 프로젝트 시트 일회성 결제. 연간 플랜·상위 티어·시트 과금 없음",
     sources=["https://www.indiehackers.com/post/xaDBfmynasknHQkim3sO",
              "https://www.indiehackers.com/post/the-exact-playbook-i-used-to-reach-1k-mrr-no-audience-no-ads-tn8xDXbSRelPtzevf3tM",
              "https://medium.com/@filip.panoski/i-built-4-saas-products-only-one-made-it-past-300-mrr-4c11ccb15d67",
              "https://github.com/filippanoski",
              "https://www.bazzly.ai/",
              "https://trustmrr.com/startup/bazzly"],
     confidence="medium"),

dict(id="idm",
     founders=["立川修平 (핸들 ぶべ)"],
     product="iDM",
     domain="Instagram DM 자동응답 SaaS",
     one_liner="Meta 공식 API 기반 인스타그램 DM 자동응답 툴 — 기존 서비스(월 22,000엔~) 대비 저가 포지셔닝",
     team_size="iDM 기준 1인 (개인개발, 운영 월 약 30분). 운영 주체는 株式会社bubekichi이며 스쿨 ShiftB·vibely·JS Gym 등 별개 사업을 함께 운영 — 순수 1인 회사는 아님",
     region="일본 도쿄",
     revenue="월 약 25만엔 (2025-10 시점, 본인 note 원문 「2025年10月時点で月に25万円程度の収益化ができています」). 후속 자가공개: 2026-04 「月30万円弱のMRR」(30만엔 미달). 원문 단어가 売上·MRR이 아니라 「収益化」이므로 '매출'로 단정하지 않는다",
     revenue_date="2025-10", exit_status="운영 중",
     stack=["Meta 공식 Instagram API"], ai_tools=["Claude Code", "Cursor"],
     founder_background="실명 立川修平 / 핸들 ぶべ. 株式会社bubekichi(2023-07 설립, 도쿄 시부야) 대표. 2020년부터 개인개발 5~6건. 개인개발 스쿨 ShiftB 운영",
     business_model="SaaS 구독 (월 3,980엔~, 14일 무료체험)",
     sources=["https://note.com/bubecode/n/n94f235367089",
              "https://note.com/bubecode/n/nb90768350a20",
              "https://note.com/bubecode/n/ncd4f31289d7c",
              "https://idm-reply.com/",
              "https://bubekichi.com/",
              "https://shiftb.dev/articles/indie-dev-success-stories"],
     confidence="medium"),

dict(id="jobric",
     founders=["Erik Chavez"],
     product="Jobric",
     domain="구직자 매칭 플랫폼",
     one_liner="Microsoft 정규직을 유지하며 2개월 만에 MRR $3.3K에 도달한 구직자 우선 매칭 서비스",
     team_size="창업자 1인 + 프랙셔널 자문 4인(보안·법무·재무·GTM) — 본인 표현 \"Team Jobric is six people today, although not everyone writes code\"",
     region="unknown",
     revenue="MRR $3,300 · 유료 구독자 약 80명 — 본인 발화 \"We launched on May 1, and we're already at $3,300 MRR\" (2026-06-26), 2026-07-14 별개 인터뷰에서 재확인. 출시(2026-05-01) 후 2개월 미만 시점 수치",
     revenue_date="2026-06", exit_status="운영 중",
     stack=["Python", "TypeScript", "Node", "Next.js", "PostgreSQL + vector search"], ai_tools=["unknown"],
     founder_background="Microsoft 재직 중(Senior Solutions Architect) — 본업 유지 사이드 프로젝트. 클라우드·플랫폼 엔지니어링 15년 이상(sysadmin → VP급 클라우드 전략)",
     business_model="구독 3단계 — Seeker 무료 / Candidate $29·월 / Contender $49·월. 분기 -15% / 6개월 -25% / 연 -33% 할인, Contender 7일 무료(카드 불필요)",
     sources=["https://www.indiehackers.com/post/eb5timbPqFlDFWZjha9i",
              "https://indieniche.substack.com/p/most-hiring-platforms-work-for-companies",
              "https://www.jobric.ai/about",
              "https://theupdate.jobric.ai/"],
     confidence="medium"),

dict(id="ai-toolbox",
     founders=["Adi Leviim", "Mohammad El-Esawi"],
     product="AI Toolbox (구 ChatGPT Toolbox)",
     domain="크롬 확장 기반 AI 유틸리티 묶음",
     one_liner="크롬 웹스토어 마켓플레이스 유통을 지렛대로 2년 만에 5자리 MRR에 도달한 2인 팀",
     team_size="2인 — 본인 발화 \"Two people, one droplet, and $45 a month, at 5-figure MRR\"",
     region="이스라엘",
     revenue="5-figure MRR (본인 표현, 정확 수치 비공개) — 하한 월 $10,000. 본인 발화 \"Less than two years later, AI Toolbox has a 5-figure MRR and over 35,000 users\" (2026-07-23). 사용자 수는 출처별 상충(IH 35,000+ / 공식 40,000+ / 크롬 웹스토어 표시 30,000)",
     revenue_date="2026-07", exit_status="운영 중",
     stack=["TypeScript (UI 프레임워크 미사용)"], ai_tools=["unknown"],
     founder_background="Adi Leviim(제품·프론트엔드, 풀스택 7년+) / Mohammad El-Esawi(백엔드·알고리즘·AI/LLM 연동, 풀스택 5년+). 제품 출시와 같은 달(2024-09) 두 사람이 세운 자기 법인 Infi Developments 소속. 동일 2인이 제3자 1인과 함께 별개 제품 Landy AI도 운영",
     business_model="프리미엄 — 모듈별 $9.99/월 또는 $59/년 또는 $99 라이프타임, All Access $199 일회성, Teams $15/시트/월. AppSumo 라이프타임 $59 병행 유통",
     sources=["https://www.indiehackers.com/post/ltsw3AYvsvslFIYZtYZG",
              "https://www.ai-toolbox.co/about",
              "https://www.ai-toolbox.co/pricing",
              "https://chromewebstore.google.com/detail/ai-toolbox-folders-prompt/jlalnhjkfiogoeonamcnngdndjbneina",
              "https://appsumo.com/products/ai-toolbox/",
              "https://il.linkedin.com/in/adi-leviim"],
     confidence="medium"),

dict(id="erik-aronesty-portfolio",
     founders=["Erik Aronesty"],
     product="OnwardTravel / DirtSignal / PrismClip (포트폴리오)",
     domain="폐기 도메인을 인수해 기존 수요 위에 재구축하는 포트폴리오 — 항공 예약 홀드 발급, 공공기록 정보 서비스",
     one_liner="정규직을 유지하며 죽은 도메인을 사들여 에이전트로 재구축하는 25년차 엔지니어의 주말 포트폴리오",
     team_size="1인 (직원 없음, Q32 LLC 단독 보유). 정규직 병행 — 주말·야간 주 30시간",
     region="미국 뉴욕",
     revenue="월 약 $15,000 — 본인 발화 \"We currently generate approximately $15k in monthly revenue\" (2026-07). **대부분 경상매출이 아니다**: 본인 발화 \"Most of that is not recurring. Travel-related systems never are.\" 구성비는 비율로만 공개됐다 — OnwardTravel 약 70%, DirtSignal 약 20%, 롱테일 약 10%. 30개 이상 사이트에서 월 매출이 발생하며 일부는 월 $60 수준",
     revenue_date="2026-07",
     exit_status="운영 중 (PrismClip은 2026-07 기준 매출 전, 이후 유료 티어 가동)",
     stack=["Cloudflare", "DigitalOcean managed Postgres", "BoxPDF(자작 OSS)", "LakeQL(자작 OSS)"],
     ai_tools=["Codex", "Claude"],
     founder_background="25년+ 경력 시니어 엔지니어. Bloomberg NLP 그룹 암호화 시스템 설계(암호학 특허·논문), 최초의 온라인 프라임 브로커리지 개발, 글로벌 DNS 기업 ZoneEdit 구축 및 .GOV TLD 운영, 보안기업 Atakama CTO. 현재 Puzzle 정규직 시니어 SWE — 이 포트폴리오는 주말·야간 사이드 프로젝트",
     business_model="OnwardTravel: 비자·입국심사의 출국편 증빙 요건 충족용 항공 예약 홀드(실제 PNR) 발급, $16 정액(전액 발권은 선택) / DirtSignal: 약 200개 지자체 코드 집행·심리 포털 스크래핑 및 정보공개청구 대행, $29/월부터 / PrismClip: 장시간 오디오·영상에서 숏폼 클립 생성, Free/$10/$20",
     sources=["https://www.indiehackers.com/post/n5NdriCp6HBqm4ApZO05",
              "https://github.com/earonesty",
              "https://q32.com",
              "https://onwardtravel.com/terms",
              "https://dirtsignal.com/updates",
              "https://prismclip.com"],
     confidence="medium"),

dict(id="zigpoll",
     founders=["Jason Zigelbaum"],
     product="Zigpoll",
     domain="Shopify 앱 설문·고객 피드백 SaaS",
     one_liner="Shopify 앱스토어에 집중해 $1.5M 런레이트에 도달한 1인 SaaS — 2019년 제품을 에이전트 코딩 루프로 개선 중",
     team_size="1인 — 본인 발화 \"I run the company solo: no cofounder, no funding, no sales team\"",
     region="미국 (뉴욕 추정 — 자기신고 미확보)",
     revenue="월 $125K MRR (2026-06) · 런레이트 약 $1.5M — 본인 발화 \"I started 2026 with about $1.03M ARR and am closing June around $125K MRR, roughly a $1.5M run rate. This represents about a 44% increase in the first half of the year.\" 본인 서술로 트랙션까지 약 2년, 이후 매년 매출 2배",
     revenue_date="2026-06", exit_status="운영 중",
     stack=["JavaScript", "Express", "MongoDB", "React", "Redis", "MCP 서버"],
     ai_tools=["Claude Code"],
     founder_background="개발자(본인 표현 \"I'm technical\"). 이전 SaaS 2건 — Metafields Manager는 Shopify가 인수, 다른 하나는 매각. 법인 Argonautic Labs",
     business_model="Shopify 앱 SaaS 구독. 무료 티어 상시 제공, 에이전시·컨설턴트가 다수 스토어에 설치하는 구조가 핵심 성장 채널",
     sources=["https://www.indiehackers.com/post/tech/hitting-125k-mrr-as-a-solo-founder-by-doubling-down-on-the-right-segment-c4o2Tfs6mjdpip5yZhaO",
              "https://honestecommerce.com/blogs/episodes/removing-buyer-friction-through-direct-feedback-jason-zigelbaum-zigpoll-bonus-episode",
              "https://apps.shopify.com/zigpoll",
              "https://docs.zigpoll.com/integrations/mcp",
              "https://github.com/JasonZigelbaum"],
     confidence="medium"),

dict(id="setter-ai",
     founders=["Josef Büttgen (기술)", "Timo Tzschetzsch (마케팅·세일즈)"],
     product="Setter AI",
     domain="WhatsApp 리드 응대 AI 에이전트 (B2B 세일즈)",
     one_liner="붕괴와 재기를 겪은 2인 팀 — 숙련 엔지니어가 AI를 '부분적으로' 쓴다고 스스로 밝힌 드문 사례",
     team_size="2인 (공동창업자 2명, 고용 인력 없음). 미펀딩 — YC 5회 지원 전부 탈락",
     region="독일 출신 2인 (Timo 방콕 / Josef 샌프란시스코 자기신고), 법인 Setter AI LLC는 미국",
     revenue="MRR $6,694 · 지난 30일 $7,192 · 누적 $206,042 · 활성 구독 20건 — **Stripe API 연동 검증치**(TrustMRR, 2026-08-13). **정점 이후 하락 중**: 2025-02 $2.4K → 2025-07 $10K → 2026-08 $6.7K. 그 전 붕괴 이력도 본인 공개 — \"$0 to $10k MRR and back to $0 — all in the timespan of six months. In August 2024, the business basically collapsed, including a nearly $5,000 dispute.\"",
     revenue_date="2026-08", exit_status="운영 중",
     stack=["SvelteKit", "TypeScript", "Tailwind", "Supabase", "Clerk", "Stripe", "OpenAI"],
     ai_tools=["Cursor", "Claude Code"],
     founder_background="Josef Büttgen — 13세부터 독학, CS 전공 엔지니어. 첫 제품 약 1년 실패 후 '12개월 12스타트업' 챌린지 중 착수. / Timo Tzschetzsch — 마케팅·세일즈 담당, 선행 제품 Jinni AI 운영",
     business_model="구독 SaaS (처리 리드 수 기반) + 고접점 고객 일회성 셋업 패키지",
     sources=["https://www.indiehackers.com/post/tech/from-desperation-and-dwindling-runway-to-10k-mrr-VRQprGga5zF3UFDqiCqw",
              "https://www.indiehackers.com/post/tech/the-journey-from-0-to-10k-to-0-and-back-to-10k-mrr-again-0qEebF7eg4ImSVFTcbj6",
              "https://www.youtube.com/shorts/NkR845KebqQ",
              "https://www.youtube.com/shorts/FeL3gt7Lp14",
              "https://trustmrr.com/startup/setter-ai-llc",
              "https://github.com/J3012B"],
     confidence="high"),

dict(id="artmvstd",
     founders=["Max Artemov"],
     product="ARTMVSTD (학습 앱 30개+ 포트폴리오)",
     domain="모바일 앱 포트폴리오 (구독 IAP 중심, ASO 주도)",
     one_liner="단일 앱 5년 실패 후 12개월간 경량 학습 앱 30개+로 전환 — 코드 90%를 복제하고 종목 전환은 AI에 맡긴다",
     team_size="1인 (정규직 병행 사이드 프로젝트)",
     region="라트비아",
     revenue="앱 30개 합산 MRR $22K (2025-12, 본인 발화). 시계열: $7K MRR (2025-10) → $22K (2025-12). **gross/net 미상** — 스토어 수수료 15~30%와 UA 지출(Apple Search Ads 월 약 €400)의 차감 여부를 밝힌 적 없다",
     revenue_date="2025-12", exit_status="운영 중 (대표 앱 2026-07-15 갱신, 500K+ 다운로드)",
     stack=["Flutter", "Firebase (Auth/Hosting/Cloud Functions)", "Fastlane", "ASO 툴 (Astro, FoxData)"],
     ai_tools=["ChatGPT"],
     founder_background="iOS 개발 경력 약 8년. 칼로리 카운터 단일 앱 5년+ 시도 후 2025-02 포트폴리오 전략으로 전환. 정규직 병행",
     business_model="앱 내 구독 IAP — 본인 발화 \"95% of all subs are weekly\", \"more than 80% of revenue comes from subscriptions\". 3일 무료체험 주간 구독 중심. 획득은 ASO 오가닉 주도, 보조로 Apple Search Ads 월 약 €400",
     sources=["https://www.indiehackers.com/post/tech/from-failed-app-to-30-app-portfolio-making-22k-mo-in-less-than-a-year-myy3U7K9evxGOVOHti8s",
              "https://www.youtube.com/watch?v=H_oRgWaslSA",
              "https://artmvstd.com/",
              "https://play.google.com/store/apps/developer?id=Artmvstd"],
     confidence="medium"),

dict(id="leadmore-ai",
     founders=["Richard Wang"],
     product="Leadmore AI",
     domain="Reddit 리드 발굴·운영 자동화 (마케팅 SaaS)",
     one_liner="런칭 4개월에 월 $30K — 오디언스도 광고비도 없이 Reddit 한 채널로 올린 크레딧 종량제 SaaS",
     team_size="창업 시점 1인 — 2025-12 글 전체가 'I'. 2026-02 이후 글부터 'we'가 등장하나 인원수 미공개",
     region="unknown",
     revenue="월 $30K 초과 (2025-12, 본인 글 제목 \"$30K MRR in 4 Months\") → 이후 ARR $1M (2026-02-11, 본인 게시물). **$1M의 산출법을 본인이 자진 공개했다** — \"The $1M ARR is based on a run rate calculation: revenue from a recent day multiplied by 365. This can be slightly higher than a strict subscription based ARR...\" 즉 최근 하루 매출 × 365이며 구독 ARR이 아니다",
     revenue_date="2026-02", exit_status="운영 중",
     stack=["Next.js", "Go (Gin)", "MongoDB", "ClickHouse", "Function Compute"],
     ai_tools=["unknown"],
     founder_background="본인 발화 \"I have over five years of experience in the internet industry, and I've worked in both engineering and product roles at leading tech companies.\" 직전 실패작(AI B2C, 약 3개월 개발 후 종료) 이력. 동일 창업자가 별개 제품 Vismore(AEO 플랫폼)도 운영",
     business_model="크레딧 기반 종량제 (미사용 크레딧 환불 가능). 2026-01경 지역별 가격제를 폐지하고 글로벌 단일가로 전환, 첫 구매가를 $9.9로 인하",
     sources=["https://www.indiehackers.com/post/tech/hitting-30k-mrr-with-an-ai-marketing-product-n59ORJCYjnZC61Q096UL",
              "https://www.indiehackers.com/post/how-i-built-a-reddit-marketing-tool-to-30k-mrr-in-4-months-with-0-spent-on-marketing-470f39b763",
              "https://www.indiehackers.com/post/i-built-a-reddit-marketing-product-leadmore-ai-and-it-just-crossed-1m-arr-f8b758eb1a",
              "https://www.indiehackers.com/Richard_ai",
              "https://leadmore.ai"],
     confidence="medium"),
]

with open("data/raw_cases.json", "w", encoding="utf-8") as f:
    json.dump(cases, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(cases)} cases")
