import json

cases = [
dict(id="base44", founders=["Maor Shlomo"], product="Base44", domain="AI 앱 빌더 (바이브코딩 플랫폼)",
     one_liner="프롬프트만으로 백엔드/DB/인증까지 포함된 풀스택 앱을 생성해주는 노코드 AI 플랫폼",
     team_size="1인 (솔로, 후반부 소수 채용)", region="이스라엘",
     revenue="월 순이익 $189,000(2025-05), 누적매출 약 $1.9M; 6개월만에 Wix에 현금 $80M + 최대 $90M 언아웃으로 인수",
     revenue_date="2025-05 / 2025-06 exit", exit_status="acquired (Wix, $80M)",
     stack=["AI 코드생성 (Claude/OpenAI 계열 추정)"], ai_tools=["Claude", "ChatGPT/OpenAI"],
     founder_background="31세 개발자, 이전에 데이터사이언스 스타트업 Explorium 공동창업(총 $125M 투자유치) 경험 있는 연쇄창업가",
     business_model="프리미엄/사용량 기반 SaaS(AI 앱 생성 크레딧)",
     sources=["https://techcrunch.com/2025/06/18/6-month-old-solo-owned-vibe-coder-base44-sells-to-wix-for-80m-cash",
               "https://www.wix.com/press-room/home/post/wix-further-expands-into-vibe-coding-with-acquisition-of-base44-a-hyper-growth-startup-that-simplif",
               "https://www.lennysnewsletter.com/p/the-base44-bootstrapped-startup-success-story-maor-shlomo"],
     confidence="high"),

dict(id="pieter-levels-portfolio", founders=["Pieter Levels"], product="Nomad List / RemoteOK / Photo AI / Interior AI (포트폴리오)",
     domain="원격근무 커뮤니티 + AI 이미지 생성 SaaS 포트폴리오",
     one_liner="디지털 노마드 커뮤니티/구인 플랫폼과 AI 사진·인테리어 생성 서비스 등 수십 개 제품을 혼자 운영",
     team_size="1인 (직원 없음, 간헐적 계약직)", region="네덜란드 (발리 거주 노마드)",
     revenue="Photo AI 18개월 만에 MRR $132K 도달; 포트폴리오 전체 연 매출 약 $3M 수준으로 다수 매체에서 인용",
     revenue_date="2023-2025 누적", exit_status="운영 중",
     stack=["PHP/SQLite", "vanilla JS/jQuery", "단일 VPS"], ai_tools=["Stable Diffusion", "DreamBooth", "Replicate", "GPT-4 API"],
     founder_background="네덜란드 출신, 유튜버에서 개발자로 전환, 70개 이상 실패작 이후 히트작들을 만든 대표적 '빌드 인 퍼블릭' 인플루언서",
     business_model="구독형 SaaS 다수 (프리미엄 티어, 무료 없음)",
     sources=["https://www.indiehackers.com/post/photo-ai-by-pieter-levels-complete-deep-dive-case-study-0-to-132k-mrr-in-18-months-3a9a2b1579",
               "https://levels.io/photoai-40870-line-index-php-105k-mo-revenue",
               "https://ppc.land/how-one-photo-ai-app-generates-132k-monthly-after-70-failed-startups/"],
     confidence="high"),

dict(id="headshotpro", founders=["Danny Postma"], product="HeadshotPro", domain="AI 프로필사진 생성",
     one_liner="링크드인/기업용 전문 프로필 사진을 AI로 생성해주는 서비스",
     team_size="1인 (솔로/매우 린)", region="네덜란드 (발리 거주)",
     revenue="월 약 $300,000 (연 $3.6M ARR 수준)", revenue_date="2024-2025", exit_status="운영 중",
     stack=["생성형 이미지 AI 모델(구체 미상세)"], ai_tools=["unknown"],
     founder_background="이전에 AI 카피라이팅 툴 Headlime을 만들어 8개월만에 약 $1M에 매각한 연쇄창업가",
     business_model="패키지 단위 일회성 결제 (AI 사진 생성 서비스)",
     sources=["https://www.starterstory.com/stories/headshotpro-breakdown",
               "https://supabird.io/articles/danny-postma-how-a-solo-hacker-built-an-ai-empire-from-bali"],
     confidence="medium"),

dict(id="cal-ai", founders=["Zach Yadegari", "Henry Langmack", "Blake Anderson", "Jake Castillo"], product="Cal AI",
     domain="AI 칼로리/영양 트래킹 앱", one_liner="음식 사진을 찍으면 AI가 칼로리/영양성분을 분석해주는 모바일 앱",
     team_size="공동창업자 4명 + 직원 소수(최대 약 8~12명)", region="미국",
     revenue="월 매출 $2M+ (2025-03 기준, 일부 소스는 연 $30-40M ARR로 인용); MyFitnessPal에 인수(2026-03, 금액 비공개)",
     revenue_date="2025-03 ~ 2026-03", exit_status="acquired (MyFitnessPal)",
     stack=["이미지인식 AI(Anthropic/OpenAI 계열)", "RAG", "오픈소스 식품DB"], ai_tools=["Anthropic", "OpenAI"],
     founder_background="공동창업자 다수가 고등학생 시절 창업; Yadegari는 16세에 이전 서비스를 $100K에 매각한 경험 있는 자수성가형 개발자",
     business_model="프리미엄 모바일 앱 구독",
     sources=["https://techcrunch.com/2025/03/16/photo-calorie-app-cal-ai-downloaded-over-a-million-times-was-built-by-two-teenagers/",
               "https://techcrunch.com/2026/03/02/myfitnesspal-has-acquired-cal-ai-the-viral-calorie-app-built-by-teens/",
               "https://www.entrepreneur.com/business-news/teen-builds-30-million-app-gets-rejected-by-15-colleges/489644"],
     confidence="high"),

dict(id="cluely", founders=["Chungin (Roy) Lee", "Neel Shanmugam", "Alex Chen"], product="Cluely",
     domain="AI 실시간 어시스턴트 (화면/오디오 모니터링 후 답변 제안)",
     one_liner="면접·회의 중 화면과 음성을 보고 실시간으로 답변을 제안해주는 투명 오버레이 AI 어시스턴트 (초기엔 '면접 커닝툴'로 시작)",
     team_size="소규모 초기팀", region="미국",
     revenue="시드 $5.3M(2025-04) + 시리즈A $15M(2025-06, a16z), 누적 $20.3M 투자유치; ARR $7M 주장했으나 실제로는 약 $5.2M로 확인됨",
     revenue_date="2025", exit_status="운영 중 (논란 있음)",
     stack=["LLM 기반"], ai_tools=["unknown"],
     founder_background="Lee와 Shanmugam은 이 제품의 전신인 'Interview Coder'(면접용 AI 부정행위 툴) 개발로 컬럼비아대에서 정학 처분",
     business_model="구독형 SaaS",
     sources=["https://en.wikipedia.org/wiki/Cluely",
               "https://www.inc.com/leila-sheridan/an-a16z-backed-startup-that-helps-people-cheat-on-job-interviews-just-got-caught-in-a-7-million-lie-the-ceo-was-sweating/91313070"],
     confidence="medium"),

dict(id="marc-lou-portfolio", founders=["Marc Lou"], product="ShipFast + 인디 제품 포트폴리오",
     domain="SaaS 보일러플레이트/스타터 킷 + 다수 소규모 앱",
     one_liner="빠른 SaaS 런칭을 위한 Next.js 보일러플레이트 판매 및 다수의 사이드 프로젝트 운영",
     team_size="1인", region="프랑스",
     revenue="ShipFast 4개월간 $528K 보고; 포트폴리오 전체 월 $100K+ 보고된 시기 있음",
     revenue_date="2023-2024", exit_status="운영 중",
     stack=["Next.js"], ai_tools=["unknown"],
     founder_background="프랑스 출신 대표적 '빌드 인 퍼블릭' 인디해커",
     business_model="보일러플레이트/템플릿 일회성 판매 + 사이드 SaaS 구독",
     sources=["https://www.starterstory.com/marc-lou-shipfast", "https://newsletter.marclou.com/p/i-made-250000-usd-selling-javascript"],
     confidence="medium"),

dict(id="tweethunter-taplio", founders=["Tibo (Thibault) Louis-Lucas"], product="Tweet Hunter / Taplio",
     domain="소셜미디어(X/LinkedIn) 성장 툴", one_liner="AI 보조 콘텐츠 작성·예약 기능으로 X/LinkedIn 퍼스널 브랜드 성장을 돕는 SaaS",
     team_size="소규모 팀 (TMAKER Studio)", region="프랑스",
     revenue="Tweet Hunter 12개월만에 ARR $1M 도달, 이후 약 $10M 규모로 SaaS 매각(exit) 보도",
     revenue_date="2022-2023", exit_status="acquired (매각, 정확한 인수자 미상세)",
     stack=["unknown"], ai_tools=["unknown"],
     founder_background="프랑스 출신 연쇄창업가, 빌드 인 퍼블릭 커뮤니티의 유명 인물",
     business_model="SaaS 구독",
     sources=["https://thebootstrappedfounder.com/thibault-louis-lucas-selling-a-10m-saas-and-building-another-one/"],
     confidence="medium"),

dict(id="lovable", founders=["Anton Osika", "Fabian Hedin"], product="Lovable (구 GPT Engineer)",
     domain="AI 바이브코딩 플랫폼", one_liner="자연어 프롬프트로 프론트엔드/백엔드/DB까지 자동 생성하는 스웨덴발 바이브코딩 유니콘",
     team_size="약 18~146명 (2025년초 18명 → 2026년초 146명으로 급성장)", region="스웨덴",
     revenue="출시 4개월만에 ARR 약 $30M; 2026-03 한 달간 매출 $100M 추가 보고; 2025-12 $330M 투자유치, 기업가치 $6.6B",
     revenue_date="2025-2026", exit_status="운영 중 (유니콘)",
     stack=["GPT 기반 자연어처리", "Supabase 연동"], ai_tools=["GPT 계열"],
     founder_background="Anton은 소프트웨어 개발자(YC 스타트업 CTO 경력), Fabian은 10세부터 창업 경험 있는 스웨덴 창업자",
     business_model="프리미엄/사용량 기반 SaaS",
     sources=["https://techcrunch.com/2026/03/11/lovable-says-it-added-100m-in-revenue-last-month-alone-with-just-146-employees/",
               "https://techcrunch.com/2025/12/18/vibe-coding-startup-lovable-raises-330m-at-a-6-6b-valuation/"],
     confidence="high"),

dict(id="bolt-new", founders=["Eric Simons"], product="Bolt.new (by StackBlitz)",
     domain="AI 바이브코딩 플랫폼", one_liner="브라우저 내에서 프롬프트로 풀스택 앱을 즉시 생성·배포하는 AI 코딩 에이전트",
     team_size="StackBlitz 소규모 코어팀", region="미국",
     revenue="출시 약 5개월만에 ARR 약 $40M 도달; 매출이 두 달만에 수천만 달러로 확대되며 $105.5M+ 투자유치",
     revenue_date="2024-2025", exit_status="운영 중",
     stack=["WebContainers(브라우저 내 실행환경)", "LLM 연동"], ai_tools=["unknown"],
     founder_background="기존 개발자도구 회사 StackBlitz의 창업자, Bolt.new는 피벗 제품",
     business_model="프리미엄/사용량 기반 SaaS",
     sources=["https://www.lennysnewsletter.com/p/inside-bolt-eric-simons"],
     confidence="medium"),

dict(id="cursor", founders=["Michael Truell", "외 3명"], product="Cursor (Anysphere)",
     domain="AI 코딩 IDE (개발자 도구)", one_liner="바이브코딩 시대에 널리 쓰이는 AI 기반 코드 에디터",
     team_size="MIT 졸업생 4인 창업팀에서 급성장", region="미국",
     revenue="2025-11 $2.3B 투자유치(기업가치 $29.3B); 2026-04 추가 $50B+ 밸류 라운드 협상 보도",
     revenue_date="2025-2026", exit_status="운영 중 (유니콘)",
     stack=["unknown"], ai_tools=["unknown"],
     founder_background="MIT 졸업생/중퇴자 4인, 현재 억만장자로 보도됨",
     business_model="개발자용 SaaS 구독",
     sources=["https://www.forbes.com/sites/rashishrivastava/2025/11/13/four-cofounders-of-popular-ai-coding-tool-cursor-are-now-billionaires/"],
     confidence="high"),

dict(id="wave-ai", founders=["Josh Mohrer"], product="Wave AI", domain="AI 음성메모/회의 요약 앱",
     one_liner="대화를 녹음·전사·요약해주는 AI 음성노트 앱, 엔지니어링부터 고객지원까지 혼자 운영",
     team_size="1인 (솔로)", region="미국",
     revenue="연 매출 약 $7M, 순이익 약 $3M (2026-02 기준)", revenue_date="2026-02", exit_status="운영 중",
     stack=["Cursor", "Claude Code(Opus)", "Next.js", "Firebase"], ai_tools=["Whisper", "AssemblyAI", "Deepgram", "Claude"],
     founder_background="전 우버 뉴욕 GM, 헬스테크 스타트업 Levels 초기 멤버, 수학 전공, 정규 엔지니어링 배경 없이 바이브코딩으로 개발",
     business_model="구독형 SaaS (주/월/연 단위)",
     sources=["https://mixergy.com/interviews/the-7-million-vibe-coded-app/"],
     confidence="high"),

dict(id="ben-broca", founders=["Ben Broca"], product="(제품명 비공개, AI 비즈니스 관리 툴)",
     domain="AI 기반 1인 비즈니스 운영 도구", one_liner="이메일·코딩·고객응대·구독관리 등을 AI로 처리해 직원 없이 운영하는 SaaS",
     team_size="1인 (유일한 직원)", region="미국",
     revenue="연 매출 $10M 목표 궤도, 유료고객 10,000명; $30M 외부투자 유치",
     revenue_date="2025-2026", exit_status="운영 중",
     stack=["unknown"], ai_tools=["이메일/코딩/고객응대용 다양한 AI 툴(구체 미상세)"],
     founder_background="40세, 재택근무로 전량 운영, WSJ 최초 보도",
     business_model="구독형 SaaS",
     sources=["https://finance.yahoo.com/small-business/articles/ben-broca-raised-30-million-143000749.html"],
     confidence="medium"),

dict(id="deep-personality", founders=["Bryce Edwards", "Andrew Wilkinson"], product="Deep Personality",
     domain="AI 성격분석/궁합 서비스", one_liner="AI 기반 성격분석 및 커플 궁합 평가 서비스",
     team_size="2인", region="미국",
     revenue="출시 30일만에 $11,000 (2025-02 런칭, 기획~출시 6주)", revenue_date="2025-02", exit_status="운영 중",
     stack=["unknown"], ai_tools=["Claude/GPT-4 계열 추정"],
     founder_background="Bryce는 이전 회사 엑싯 경험, Andrew Wilkinson은 유명 연쇄창업가/투자자",
     business_model="프리미엄 (약 40% 무료, 전체 리포트는 유료)",
     sources=["https://www.indiehackers.com/post/from-0-to-11k-in-30-days-with-a-vibe-coded-ai-personality-analysis-b9ad81d534"],
     confidence="high"),

dict(id="dreamgf", founders=["Georgi Dimitrov"], product="DreamGF", domain="AI 컴패니언(가상 여자친구) 앱",
     one_liner="커스터마이징 가능한 AI 챗봇+이미지생성 가상 컴패니언 서비스", team_size="unknown", region="불가리아 추정",
     revenue="월 약 $120,000, 등록 유저 50만명, 유료고객 1만명, 출시 3개월만에 흑자전환",
     revenue_date="2025", exit_status="운영 중",
     stack=["Stable Diffusion", "ChatGPT 계열"], ai_tools=["Stable Diffusion", "ChatGPT"],
     founder_background="이전에 OnlyFans 크리에이터 에이전시 근무 경험", business_model="구독 티어제 (€10~€97/월, Patreon 결제)",
     sources=["https://sifted.eu/articles/ai-girlfriends"], confidence="medium"),

dict(id="appalchemy", founders=["Diego Roshardt"], product="AppAlchemy", domain="브라우저 기반 모바일 앱 빌더",
     one_liner="다운로드 없이 브라우저에서 네이티브 앱을 만드는 노코드 앱 빌더", team_size="1인", region="unknown",
     revenue="출시 12개월만에 MRR $10,000+", revenue_date="2024-2025", exit_status="운영 중",
     stack=["Next.js", "Supabase", "Claude Code", "Cursor", "React"], ai_tools=["Claude Code", "Cursor"],
     founder_background="독학(유튜브), 대학 때부터 프로젝트 진행, 스타트업 SWE로 잠깐 근무 후 풀타임 전환",
     business_model="구독형(월+할인 연간)",
     sources=["https://www.indiehackers.com/post/tech/launching-an-app-builder-in-2-weeks-and-hitting-10k-mrr-within-a-year-gRWT2S68TIQwMvb6Xxt4"],
     confidence="high"),

dict(id="launch-fast", founders=["Hasaam Bhatti"], product="Launch Fast", domain="아마존 셀러용 AI 리서치 툴",
     one_liner="아마존 셀러를 위한 상품 리서치/카탈로그관리/광고최적화 크롬 확장 프로그램",
     team_size="unknown (매우 소규모 추정)", region="unknown",
     revenue="런칭 30일 $10K → 60일 $17-18K → 90일 $21.8K → 현재 MRR $30K", revenue_date="2025", exit_status="운영 중",
     stack=["Cursor", "Next.js/React/TS", "Vercel", "Supabase", "Cloudflare", "Codex", "Claude Code"],
     ai_tools=["Codex", "Claude Code", "Cursor"],
     founder_background="비개발자, 아마존 FBA 셀러 출신, 이전에 10~12개 실패한 프로젝트 경험",
     business_model="티어형 구독($49/$89/$199, 무료 티어 없음)",
     sources=["https://www.indiehackers.com/post/tech/building-a-product-in-48-hours-and-hitting-30k-mrr-as-a-non-technical-founder-wWtWIH5tmwASUbxKaLT9"],
     confidence="high"),

dict(id="sleek-design", founders=["Mattia Pomelli", "외 2명(친구)"], product="Sleek (sleek.design)",
     domain="AI 모바일 UI 디자인 툴", one_liner="대화형으로 앱 UI를 디자인해주는 '바이브 디자인' AI 툴, 코딩/디자인 지식 불필요",
     team_size="3인", region="unknown",
     revenue="출시 6주만에 MRR $10,000, 유료마케팅 없이 달성", revenue_date="2024-2025", exit_status="운영 중",
     stack=["Next.js", "Supabase", "Vercel", "PostHog", "Stripe", "Resend"], ai_tools=["unknown"],
     founder_background="8년 코딩 경력, 팀원들과 이전에 디자인 툴 4개를 함께 만든 경험",
     business_model="AI 크레딧 기반 구독 티어, 제한적 무료 티어",
     sources=["https://www.indiehackers.com/post/tech/hitting-10k-mrr-in-six-weeks-with-an-ai-design-tool-pEvmU5qkWS6ny0AR9SUv"],
     confidence="high"),

dict(id="habit-pixel", founders=["Hirvesh Munogee"], product="Habit Pixel", domain="습관 트래커 앱",
     one_liner="픽셀아트 게이미피케이션 요소가 있는 크로스플랫폼 습관 트래커", team_size="1인", region="모리셔스",
     revenue="6개월 MRR $28 → 11월 $407 → 12월 $840 → 이듬해 1월 $1,000+ MRR", revenue_date="2025-06~2026-01",
     exit_status="운영 중", stack=["unknown"], ai_tools=["unknown"],
     founder_background="독학 개발자, 본인의 습관형성 어려움을 해결하려고 제작",
     business_model="프리미엄 ($4.99/월 또는 $29.99/년, PPP 가격, 블프 라이프타임 프로모션)",
     sources=["https://www.indiehackers.com/post/from-0-to-1k-mrr-in-8-months-bootstrapping-habit-pixel-as-a-solo-dev-53d8687d15"],
     confidence="high"),

dict(id="subscribr", founders=["Gil Hildebrand", "(18개월 후 공동창업자 합류)"], product="Subscribr",
     domain="유튜버용 AI 콘텐츠 기획 툴", one_liner="유튜브 크리에이터의 영상 아이디어/패키징/스크립트 기획을 돕는 AI 툴",
     team_size="처음엔 1인, 이후 2인", region="unknown",
     revenue="사전판매 $20K → 퍼블릭 런칭 100일만에 MRR $10K → 현재 MRR $62K+ → 1년차 $500K+, 2년차 $1M+ 목표",
     revenue_date="2024-2025", exit_status="운영 중",
     stack=["Laravel", "Livewire", "Laravel Horizon", "단일 DigitalOcean droplet"], ai_tools=["unknown"],
     founder_background="25년 이상 코딩 경력, 세스 고딘의 회사 Squidoo 전 CTO(3인 엔지니어링팀으로 연매출 $10M 달성 경험), VC 투자받은 크립토 스타트업 경력",
     business_model="SaaS 구독($49+/월), 라이프타임딜/AppSumo, 제휴 프로그램",
     sources=["https://www.indiehackers.com/post/tech/hitting-125k-mrr-as-a-solo-founder-by-doubling-down-on-the-right-segment-c4o2Tfs6mjdpip5yZhaO"],
     confidence="medium"),

dict(id="samuel-rondot-portfolio", founders=["Samuel Rondot"], product="StoryShort.ai / UseArtemis / Capacity.so",
     domain="SaaS 포트폴리오(AI 숏폼영상생성/아웃리치툴/AI코딩툴)",
     one_liner="검증된 서비스를 벤치마킹해 복제·개선하는 방식으로 여러 SaaS를 운영하는 1인 포트폴리오",
     team_size="대부분 1인 (Capacity는 고교 동창과 공동창업)", region="프랑스 추정",
     revenue="StoryShort ~$20K/월, UseArtemis ~$5-15K/월, Capacity ~$0.9-3K/월, 합계 월 $28-35K; 이전 제품 MathPlanner는 월 $30K 달성",
     revenue_date="2025-12", exit_status="운영 중",
     stack=["Next.js", "Node.js", "MongoDB", "Vercel/AWS"], ai_tools=["unknown"],
     founder_background="전직 안경사(의료계), 유튜브 독학으로 코딩 습득, 인스타그램 자동화 서비스 운영 후 SaaS로 전환",
     business_model="SaaS 구독",
     sources=["https://www.indiehackers.com/post/tech/learning-to-code-and-building-a-28k-mo-portfolio-of-saas-products-OA5p18fXtvHGxP9xTAwG",
               "https://maily.so/josh/posts/5xrx6lnqr2v"],
     confidence="medium"),

dict(id="lancer", founders=["Ivan Nedelkovski"], product="Lancer", domain="프리랜서용 AI 리드젠 에이전트",
     one_liner="Upwork에서 프리랜서의 리드 발굴과 제안서 제출을 자동화하는 AI 에이전트", team_size="2인", region="unknown",
     revenue="런칭 60일만에 MRR $10K → $20K → 현재 $25K+/월", revenue_date="2025", exit_status="운영 중",
     stack=["GCP", "Firestore", "Hetzner", "TypeScript/Node/Next.js", "Elasticsearch", "Openrouter"],
     ai_tools=["Openrouter(AI 라우팅)"],
     founder_background="대학 두 번 중퇴, 개발 컨설팅 회사(MVP Masters)를 15명/7자리수 매출 규모로 키운 뒤 2025년 매각한 경험",
     business_model="구독 티어(Pay-per-Lead $149/월, Unlimited $499/월) + 제휴 코칭",
     sources=["https://www.indiehackers.com/post/tech/exiting-his-agency-and-hitting-10k-mrr-within-60-days-of-launching-his-saas-sTo5m9qfhxXbruvhBIyH"],
     confidence="high"),

dict(id="creator-buddy", founders=["Alex Finn"], product="Creator Buddy", domain="AI 콘텐츠 생성 툴 (X/Twitter)",
     one_liner="X(트위터) 게시물을 분석해 개인화된 콘텐츠를 생성해주는 AI 도구", team_size="1인 (직원 0명)", region="unknown",
     revenue="10개월만에 ARR $300K", revenue_date="2025", exit_status="운영 중",
     stack=["Next.js", "Vercel", "Supabase", "Claude Code"], ai_tools=["Claude Code"],
     founder_background="비개발자 출신", business_model="SaaS + 유료 '바이브코딩 아카데미' + 뉴스레터",
     sources=["https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="medium"),

dict(id="vibed-agents", founders=["Paulius (@0xPaulius)"], product="Vibed Agents", domain="자율 코딩 에이전트 플랫폼",
     one_liner="자율 코딩 에이전트를 배포해 앱을 만들어주는 플랫폼", team_size="1인", region="unknown",
     revenue="MRR $9K, 누적 $100K+, 10개 이상 앱에 걸쳐 유저 3만명+", revenue_date="2025", exit_status="운영 중",
     stack=["Claude Code", "MCP"], ai_tools=["Claude Code"],
     founder_background="런칭 9개월 전까지 커밋 경험 없는 비개발자", business_model="플랫폼/SaaS",
     sources=["https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="medium"),

dict(id="plinq", founders=["Sabrine Matos"], product="Plinq", domain="데이팅 안전 앱",
     one_liner="상대방을 공개 범죄기록과 대조 확인해주는 데이팅 안전 앱(위험도 평가, 패닉버튼 등)",
     team_size="unknown (프리시드 투자 유치 중)", region="브라질",
     revenue="ARR $456,000, 유저 1만명+, 45일만에 개발", revenue_date="2025", exit_status="운영 중",
     stack=["Lovable"], ai_tools=["Lovable"],
     founder_background="브라질의 그로스마케터, 코딩 경험 전무", business_model="구독/건당 확인 수수료",
     sources=["https://everydayaiblog.com/vibe-coded-apps-real-revenue-users/"], confidence="medium"),

dict(id="klar", founders=["Andreas", "Isabel", "Eric"], product="Klar", domain="AI 교육 플랫폼",
     one_liner="대학생들이 만든 AI 학습 시스템", team_size="3인 (대학생)", region="unknown",
     revenue="출시 30일만에 ARR €130,000, 이후 인수 제안 받음", revenue_date="2025", exit_status="운영 중(인수 제안)",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="대학생 3인 공동창업",
     business_model="AI 교육 플랫폼 구독", sources=["https://founder-stories-showcase.lovable.app/"], confidence="low"),

dict(id="quicktables", founders=["Jaleel", "Hussein", "Morten", "Zanyar"], product="QuickTables", domain="레스토랑 관리 플랫폼",
     one_liner="레스토랑 운영 관리 SaaS", team_size="4인", region="unknown",
     revenue="2개월만에 ARR €100,000, 이후 인수됨", revenue_date="2025", exit_status="acquired",
     stack=["Lovable"], ai_tools=["Lovable"], founder_background="unknown",
     business_model="레스토랑 운영 소프트웨어 구독", sources=["https://founder-stories-showcase.lovable.app/"], confidence="low"),

dict(id="appbilchat", founders=["박현중"], product="앱빌챗", domain="AI 앱 개발 대행 SaaS (한국)",
     one_liner="채팅으로 아이디어를 설명하면 AI PM이 요구사항을 구조화하고 AI+엔지니어 협업으로 앱 개발부터 출시·서버운영까지 대행",
     team_size="unknown (법인, AI+인간 엔지니어 협업 구조)", region="한국",
     revenue="unknown (법인 설립 3개월만에 프리시드 투자유치, 4개월만에 TIPS 선정)", revenue_date="2026", exit_status="운영 중",
     stack=["자체 AI PM + AI/엔지니어 협업 개발"], ai_tools=["unknown"],
     founder_background="대학 시절부터 프리미엄 배송·리셀 플랫폼 등 연쇄창업 및 엑싯 경험, 2023년 오픈소스 LLM 공개 이후 AI 개발 확신을 갖게 됨",
     business_model="구독형 앱 개발 대행 서비스(B2B/B2C)",
     sources=["https://zdnet.co.kr/view/?no=20260617083532"], confidence="medium"),

dict(id="gendy", founders=["어보브테크 공동창업팀"], product="젠디(Gendy)", domain="AI 컴패니언 상담 콘텐츠 (한국)",
     one_liner="사주·헤어·심리·타로 등을 다루는 AI 컴패니언 상담 콘텐츠 플랫폼", team_size="unknown (소규모 추정)", region="한국",
     revenue="런칭 6개월만에 월 1억원(이전 월 3천→5천만원 단계 거침), 회원 4만명, 유료전환율 약 30%",
     revenue_date="2026", exit_status="운영 중",
     stack=["GPT Pro", "Cursor", "Perplexity", "LLM 챗봇", "스레드 API 자동화 마케팅"], ai_tools=["GPT Pro", "Cursor", "Perplexity"],
     founder_background="2020년 마스크 알리미 서비스 개발 경험, 블록체인 B2B 사업(연매출 30억) 경력",
     business_model="앱 내 AI 상담 콘텐츠 유료 판매",
     sources=["https://maily.so/unsexybusinesskr/posts/92zew8j7zep"], confidence="medium"),

dict(id="relic-ai", founders=["뤼튼/보이저엑스 출신 공동창업자 2인"], product="릴리스 AI (Relic AI)", domain="AI 유튜브 요약 서비스 (한국)",
     one_liner="유튜브 영상을 한국어로 요약해주는 AI 서비스", team_size="2인", region="한국",
     revenue="출시 6개월 시점 월 1,000만원, 사용자 14만명 이상", revenue_date="2025-2026", exit_status="운영 중",
     stack=["LLM 기반 요약"], ai_tools=["unknown"],
     founder_background="뤼튼(Wrtn), 보이저엑스 출신 개발자", business_model="페이드마케팅·투자 없이 유기적 성장(구독/이용료 추정)",
     sources=["https://eopla.net/magazines/15235", "https://disquiet.io/articles/W9sy71"], confidence="medium"),

dict(id="trend-widget", founders=["맥그리(닉네임)"], product="실검위젯", domain="실시간 검색어/뉴스 위젯 앱 (한국)",
     one_liner="스마트폰 홈화면 위젯으로 실시간 검색어와 AI 요약 뉴스를 제공", team_size="1인 추정", region="한국",
     revenue="unknown (다운로드 2만+, DAU 4,000명 이상)", revenue_date="2025-2026", exit_status="운영 중",
     stack=["KIRO(무료 AI 코드 어시스턴트)", "Cursor AI"], ai_tools=["KIRO", "Cursor AI"],
     founder_background="개발경력 8~9년의 현직/전직 개발자",
     business_model="unknown (인앱, 토스 미니앱 연동 계획)",
     sources=["https://www.gpters.org/dev/post/service-created-vibe-coding-x5dpT0BzKfnigQG"], confidence="low"),

dict(id="my-askai", founders=["Mike Heap", "Alex Rainey"], product="My AskAI", domain="AI 고객상담 챗봇",
     one_liner="웹사이트 콘텐츠를 학습해 응답하는 AI 고객상담 챗봇 서비스", team_size="초기 2인, 고객 12,000명 보유",
     region="unknown", revenue="월 약 5천만원 (연 약 6억원)", revenue_date="unknown", exit_status="운영 중",
     stack=["Bubble(노코드)", "ChatGPT"], ai_tools=["ChatGPT"],
     founder_background="회계사, 컨설턴트 출신(비개발자)", business_model="SaaS 구독, 2주마다 웹사이트 자동 재학습",
     sources=["https://eopla.net/magazines/32478"], confidence="low"),

dict(id="flexiple", founders=["unknown"], product="Flexiple", domain="프리랜서 개발자 매칭 플랫폼",
     one_liner="상위 1% 프리랜서 개발자와 기업을 매칭", team_size="1인(창업 초기)", region="unknown",
     revenue="연 30억원 이상", revenue_date="unknown", exit_status="운영 중",
     stack=["Unicorn Platform", "Webflow", "Airtable", "Zapier", "Memberstack (노코드)"], ai_tools=["unknown"],
     founder_background="unknown", business_model="매칭 수수료",
     sources=["https://maily.so/unsexybusinesskr/posts/32z8pd0jrn4"], confidence="low"),

dict(id="formula-bot", founders=["unknown (10년차 데이터 분석가)"], product="Formula Bot", domain="AI 엑셀/SQL 함수 생성",
     one_liner="엑셀/SQL 함수를 AI로 자동 생성해주는 서비스", team_size="1인", region="unknown",
     revenue="연 4억원", revenue_date="unknown", exit_status="운영 중",
     stack=["Bubble(노코드)", "OpenAI API"], ai_tools=["OpenAI API"],
     founder_background="데이터 분석가 출신", business_model="구독료 기반 SaaS",
     sources=["https://maily.so/unsexybusinesskr/posts/32z8pd0jrn4"], confidence="low"),

dict(id="ai-coding-consultancy", founders=["Prajwal Tomar"], product="Ignyt Labs / AI MVP Builders", domain="AI 활용 MVP 개발 에이전시",
     one_liner="AI 툴을 활용해 21일만에 클라이언트 MVP를 만들어주는 컨설팅 시스템", team_size="unknown(에이전시)", region="unknown",
     revenue="unknown (45개 이상 MVP 납품)", revenue_date="unknown", exit_status="운영 중",
     stack=["Lovable", "Cursor+Claude Code", "CodeRabbit"], ai_tools=["Lovable", "Cursor", "Claude Code"],
     founder_background="unknown", business_model="컨설팅/에이전시",
     sources=["https://iamjohnellison.substack.com/p/the-vibe-coding-wave-is-here-5-builders"], confidence="low"),

dict(id="anything", founders=["Dhruv Amin", "Marcus Lowe"], product="Anything", domain="AI 코딩 플랫폼",
     one_liner="AI 코딩 플랫폼 스타트업(엔드유저 제품이 아닌 플랫폼 자체), 출시 2주만에 ARR $2M",
     team_size="unknown", region="미국",
     revenue="출시 2주만에 ARR $2M, 기업가치 $100M", revenue_date="2025-09", exit_status="운영 중",
     stack=["unknown"], ai_tools=["unknown"], founder_background="구글 출신 공동창업자들",
     business_model="AI 코딩 플랫폼 SaaS",
     sources=["https://techcrunch.com/2025/09/29/vibe-coding-startup-anything-nabs-a-100m-valuation-after-hitting-2m-arr-in-its-first-two-weeks/"],
     confidence="medium"),

dict(id="simon-berg-portfolio", founders=["Simon Berg"], product="Frame My Home / Spellbound (MSH Studios)",
     domain="AI 인테리어 아트 프린트 / AI 교육 앱", one_liner="집·반려동물 사진을 AI 아트 액자로, 철자 학습지를 인터랙티브 게임으로 변환",
     team_size="제품당 1~2인", region="영국",
     revenue="신규 벤처 매출 비공개 (이전 회사 Ceros는 연 매출 약 $60M까지 성장 후 지분 58% 매각)", revenue_date="2025-2026",
     exit_status="운영 중", stack=["Bolt.new", "Stripe", "11 Labs", "AI 에이전트"], ai_tools=["Bolt.new"],
     founder_background="17세에 영국 크리에이티브 에이전시 사환으로 시작, Ceros를 12년간 $30K에서 $60M ARR로 키운 뒤 2020년 매각, 현재 AI 인큐베이터 MSH Studios 운영",
     business_model="Frame My Home=주문제작 프린트, Spellbound=교육 구독",
     sources=["https://bolt.new/blog/how-ceo-built-two-businesses-with-bolt"], confidence="high"),
]

with open("data/raw_cases.json", "w", encoding="utf-8") as f:
    json.dump(cases, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(cases)} cases")
